// Code generated by rotini; DO NOT EDIT.
package rth

import (
	"github.com/go-rotini/rotini"
	"github.com/go-rotini/rotini/rtg"
)

type handlers struct{}

var _ rtg.ProgramHandlers = (*handlers)(nil)

var Program = rtg.NewProgram(&handlers{})

func Handlers() rtg.ProgramHandlers {
	return &handlers{}
}

func (*handlers) Mycli() rotini.CommandHandlers {
	return &mycliHandlers{}
}
