// Code generated by rotini; DO NOT EDIT.
package demo

import (
	"github.com/go-rotini/rotini"
)

type ProgramHandlers interface {
	Demo() rotini.Handler
	DemoBuild() rotini.Handler
}

var definition = rotini.Definition{
	Name:    "demo",
	Handler: "Demo",
	Flags: []rotini.FlagDef{
		{Name: "verbose", Identifiers: []string{"--verbose", "-v"}, Summary: "verbose output", Type: "bool"},
	},
	Commands: []rotini.CommandDef{
		{Name: "build",
			Handler: "DemoBuild",
			Summary: "build the target",
			Flags: []rotini.FlagDef{
				{Name: "out", Identifiers: []string{"--out", "-o"}, Summary: "output path", Type: "string"},
				{Name: "sort-by", Identifiers: []string{"--sort-by"}, Summary: "ordering", Type: "string"},
			},
			Arguments: []rotini.ArgDef{
				{Name: "target", Type: "string"},
			},
		},
	},
}

type DemoFlags struct {
	Verbose bool `rotini:"verbose"`
}

type DemoArguments struct{}

type DemoEnv struct {
	Home    string `rotini:"home" recon:"home" env:"DEMO_HOME"`
	BaseURL string `rotini:"base_url" recon:"base_url" env:"DEMO_BASE_URL"`
	APIKey  string `rotini:"apiKey" recon:"apiKey" env:"DEMO_API_KEY"`
}

type DemoCommandInputs struct {
	Flags     DemoFlags
	Arguments DemoArguments
	Env       DemoEnv
}

type DemoInputs struct {
	Demo DemoCommandInputs
}

type DemoBuildFlags struct {
	Out    string `rotini:"out"`
	SortBy string `rotini:"sort-by" recon:"build.sort_by" env:"DEMO_BUILD_SORT_BY"`
}

type DemoBuildArguments struct {
	Target string `rotini:"target"`
}

type DemoBuildCommandInputs struct {
	Flags     DemoBuildFlags
	Arguments DemoBuildArguments
}

type DemoBuildInputs struct {
	Demo      DemoCommandInputs
	DemoBuild DemoBuildCommandInputs
}

// InputSettings is the generated descriptor the default input reader (rotini.InputReader) reads.
var InputSettings = rotini.InputSettings{
	EnvPrefix: "DEMO",
}

// NewProgram builds the program from the generated command tree and the typed
// ProgramHandlers. Construct your program with this so the compiler verifies your handlers
// satisfy ProgramHandlers; the command tree stays an unexported implementation detail.
func NewProgram(handlers ProgramHandlers) *rotini.Program {
	// InputSettings is a DESCRIPTION of this program, like the command tree above it, so it
	// travels as a typed option rather than as a registry entry — the registry is yours.
	return rotini.NewProgram(definition, handlers).
		WithInputSettings(InputSettings)
}

// handlers is the generated ProgramHandlers implementation: each method wires a command to its
// handler, whether a local type or a composed command's delegated package. Program is the
// ready-to-run program, and Handlers returns a fresh value.
//
// Every method below returns a NEW handler per call, which is what makes a handler's fields
// per-run state: the runtime asks once per command per run and uses what it gets. If you supply
// your own ProgramHandlers instead of this one, keep that property — a method returning a shared
// value makes its handler's fields shared across runs, and a data race under concurrent ones.
type handlers struct{}

var _ ProgramHandlers = (*handlers)(nil)

var Program = NewProgram(&handlers{})

func Handlers() ProgramHandlers {
	return &handlers{}
}

func (*handlers) Demo() rotini.Handler {
	return &demoHandler{}
}

func (*handlers) DemoBuild() rotini.Handler {
	return &demoBuildHandler{}
}
