// Code generated by rotini; DO NOT EDIT.
package demo

import (
	"github.com/go-rotini/rotini"
)

type ProgramHandlers interface {
	Demo() rotini.Handlers
	DemoBuild() rotini.Handlers
}

var definition = rotini.Definition{
	Name:    "demo",
	Handler: "Demo",
	Flags: []rotini.FlagDef{
		{Name: "verbose", Identifiers: []string{"--verbose", "-v"}, Summary: "verbose output", Type: "bool"},
	},
	Commands: []rotini.CommandDef{
		{Name: "build",
			Handler: "DemoBuild",
			Summary: "build the target",
			Flags: []rotini.FlagDef{
				{Name: "out", Identifiers: []string{"--out", "-o"}, Summary: "output path", Type: "string"},
			},
			Arguments: []rotini.ArgDef{
				{Name: "target", Type: "string"},
			},
		},
	},
}

type DemoFlags struct {
	Verbose bool `rotini:"verbose"`
}

type DemoArguments struct{}

type DemoEnv struct {
	Home string `rotini:"home" recon:"home" env:"DEMO_HOME"`
}

type DemoCommandInputs struct {
	Flags     DemoFlags
	Arguments DemoArguments
	Env       DemoEnv
}

type DemoInputs struct {
	Demo DemoCommandInputs
}

type DemoBuildFlags struct {
	Out string `rotini:"out"`
}

type DemoBuildArguments struct {
	Target string `rotini:"target"`
}

type DemoBuildCommandInputs struct {
	Flags     DemoBuildFlags
	Arguments DemoBuildArguments
}

type DemoBuildInputs struct {
	Demo      DemoCommandInputs
	DemoBuild DemoBuildCommandInputs
}

// BindMeta is the generated descriptor the default binder (rotini.Binder) consumes.
var BindMeta = rotini.BindMeta{}

// NewProgram builds the program from the generated command tree and the typed
// ProgramHandlers. Construct your program with this so the compiler verifies your handlers
// satisfy ProgramHandlers; the command tree stays an unexported implementation detail.
func NewProgram(handlers ProgramHandlers) *rotini.Program {
	// BindMeta rides the registry so the per-channel input functions need only the Context.
	return rotini.NewProgram(definition, handlers).
		Bind(rotini.KeyBindMeta, BindMeta)
}

// handlers is the generated ProgramHandlers implementation: each method wires a command to its
// handler, whether a local type or a composed command's delegated package. Program is the
// ready-to-run program, and Handlers returns a fresh value.
type handlers struct{}

var _ ProgramHandlers = (*handlers)(nil)

var Program = NewProgram(&handlers{})

func Handlers() ProgramHandlers {
	return &handlers{}
}

func (*handlers) Demo() rotini.Handlers {
	return &demoHandlers{}
}

func (*handlers) DemoBuild() rotini.Handlers {
	return &demoBuildHandlers{}
}
