package codegen

import (
	"flag"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// The handler stubs each root shape seeds are pinned as golden files: every file a fresh
// generate writes except the generated one. testdata/stubshapes/<case>/spec.yaml is the spec,
// and want/ holds the stubs. Refresh with
// `go test ./internal/codegen -run StubShapes -update-stubshapes`.
var updateStubShapes = flag.Bool("update-stubshapes", false, "rewrite the stub-shape golden files")

// frozenShape is generated by the published v1.2.0 tool; its golden files prove a project that
// doesn't opt into the v1.3 shape gets the same stubs, so -update-stubshapes leaves it alone.
const frozenShape = "v1.2-shape"

const stubShapesConf = goldenConf + `  features:
    - type: help
      enabled: true
`

func TestStubShapes(t *testing.T) {
	cases, err := os.ReadDir("testdata/stubshapes")
	if err != nil {
		t.Fatal(err)
	}
	for _, c := range cases {
		t.Run(c.Name(), func(t *testing.T) {
			dir, err := filepath.Abs(filepath.Join("testdata/stubshapes", c.Name()))
			if err != nil {
				t.Fatal(err)
			}
			spec, err := os.ReadFile(filepath.Join(dir, "spec.yaml"))
			if err != nil {
				t.Fatal(err)
			}
			got := map[string]string{}
			for name, body := range emitInModule(t, string(spec), stubShapesConf) {
				if !strings.HasPrefix(filepath.Base(name), "zz_") {
					got[filepath.ToSlash(name)] = body
				}
			}
			want := filepath.Join(dir, "want")
			if *updateStubShapes && c.Name() != frozenShape {
				if err := os.RemoveAll(want); err != nil {
					t.Fatal(err)
				}
				for name, body := range got {
					writeTestFile(t, want, name, body)
				}
				return
			}
			compareTree(t, want, got)
		})
	}
}

// compareTree reports each file of got that differs from, is missing from, or is extra to the
// golden files under dir.
func compareTree(t *testing.T, dir string, got map[string]string) {
	t.Helper()
	wantFiles := map[string]string{}
	err := filepath.WalkDir(dir, func(p string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		body, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(dir, p)
		wantFiles[filepath.ToSlash(rel)] = string(body)
		return nil
	})
	if err != nil {
		t.Fatalf("read %s (run with -update-stubshapes to create it): %v", dir, err)
	}
	names := make([]string, 0, len(got))
	for name := range got {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		want, ok := wantFiles[name]
		switch {
		case !ok:
			t.Errorf("generated %s, which the golden files don't have", name)
		case want != got[name]:
			t.Errorf("%s differs from the golden file:\n--- got ---\n%s\n--- want ---\n%s", name, got[name], want)
		}
		delete(wantFiles, name)
	}
	for name := range wantFiles {
		t.Errorf("did not generate %s", name)
	}
}
