package codegen

import (
	"fmt"
	"regexp"
	"slices"
	"strings"
	"text/template"
)

// The permissions feature: permission rules for agent harnesses, from the commands' effects.
// Every rule is for a leaf command offered to agents: harnesses match the start of the command
// text, so a rule for the root or a group would also match every sub-command. A command whose
// worst case is read is allowed; a destructive one asks first; a write command, or one without
// effects, gets no rule, so the harness asks as it does by default.

// permissionFiles names each harness's file; %s is the root command's name.
var permissionFiles = map[string]string{"claude": "claude-settings.json", "codex": "%s.rules", "gemini": "%s-policy.toml"}

// permissionRule is one leaf command's rule: allow it, ask before it, or ask before it only
// when one of raising's flags is given.
type permissionRule struct {
	cmd       agentCommand
	spellings []string // each way to type it
	decision  string   // "allow", "ask", or "" (no rule for the command itself)
	raising   []string // identifiers of flags that make an allowed-looking command destructive
}

// renderPermissions writes one file per harness.
func renderPermissions(_ *program, f *Feature, a *agentProgram, _ *template.Template) (map[string][]byte, []error, error) {
	harnesses := f.Harnesses
	if len(harnesses) == 0 {
		harnesses = []string{"claude", "codex", "gemini"}
	}
	rules := permissionRules(a)
	files := map[string][]byte{}
	for _, h := range harnesses {
		name := permissionFiles[h]
		if strings.Contains(name, "%s") {
			name = fmt.Sprintf(name, a.doc.Name)
		}
		switch h {
		case "claude":
			files[name] = claudePermissions(rules)
		case "codex":
			files[name] = codexRules(rules)
		case "gemini":
			files[name] = geminiPolicy(rules)
		}
	}
	return files, nil, nil
}

// permissionRules works out each offered leaf command's rule.
func permissionRules(a *agentProgram) []permissionRule {
	var out []permissionRule
	for _, c := range a.offered() {
		if !c.leaf || c.effects == nil {
			continue
		}
		r := permissionRule{cmd: c, spellings: commandSpellings(a, c)}
		switch {
		case c.effects.Kind == "read":
			r.decision = "allow"
		case c.effects.Kind == "destructive" && c.c.Effects.Kind == "destructive":
			r.decision = "ask"
		case c.effects.Kind == "destructive":
			// Only some flags make it destructive: ask when one is given.
			for _, fl := range c.c.Flags {
				if fl.Effects != nil && fl.Effects.Kind == "destructive" && toolFlagOffered(fl) {
					r.raising = append(r.raising, fl.Identifiers...)
				}
			}
		}
		if r.decision != "" || len(r.raising) > 0 {
			out = append(out, r)
		}
	}
	return out
}

// claudePermissions is a fragment to merge into Claude Code's .claude/settings.json. Ask rules
// win over allow rules, so a raising flag's rule is safe beside the command's.
func claudePermissions(rules []permissionRule) []byte {
	allow, ask := []string{}, []string{}
	for _, r := range rules {
		for _, s := range r.spellings {
			switch r.decision {
			case "allow":
				allow = append(allow, "Bash("+s+" *)")
			case "ask":
				ask = append(ask, "Bash("+s+" *)")
			}
			for _, id := range r.raising {
				ask = append(ask, "Bash("+s+" *"+id+"*)")
			}
		}
	}
	perms := map[string]any{}
	if len(allow) > 0 {
		perms["allow"] = allow
	}
	if len(ask) > 0 {
		perms["ask"] = ask
	}
	return marshalJSONFile(map[string]any{"permissions": perms})
}

// codexRules is a Codex rules file (Starlark prefix_rule calls). A prefix rule can't see flags
// later on the line, so a command that a flag can make destructive prompts as a whole. Each
// rule's match and not_match examples are checked when Codex loads the file.
func codexRules(rules []permissionRule) []byte {
	var b strings.Builder
	b.WriteString("# Codex rules generated by rotini from the commands' effects. Copy this file to\n# ~/.codex/rules/ (or a project's .codex/rules/).\n")
	for _, r := range rules {
		decision := map[string]string{"allow": "allow", "ask": "prompt", "": "prompt"}[r.decision]
		why := "read-only"
		if decision == "prompt" {
			why = "destructive"
			if r.decision == "" {
				why = "destructive with " + strings.Join(r.raising, ", ")
			}
		}
		justification := strings.TrimSpace(r.cmd.c.Summary)
		if justification == "" {
			justification = r.cmd.invocation
		}
		fmt.Fprintf(&b, "\nprefix_rule(\n    pattern = %s,\n    decision = %q,\n    justification = %s,\n    match = [%s],\n",
			codexPattern(r), decision, starlarkString(justification+" ("+why+")"), starlarkString(r.cmd.invocation))
		if len(r.cmd.c.Path) > 0 {
			parent := strings.Join(r.cmd.words[:len(r.cmd.words)-1], " ")
			fmt.Fprintf(&b, "    not_match = [%s],\n", starlarkString(parent))
		}
		b.WriteString(")\n")
	}
	return []byte(b.String())
}

// codexPattern is a rule's pattern: one element per word, with a word's aliases as
// alternatives.
func codexPattern(r permissionRule) string {
	alts := make([][]string, len(r.cmd.words))
	for _, s := range r.spellings {
		for i, w := range strings.Fields(s) {
			if i < len(alts) && !slices.Contains(alts[i], w) {
				alts[i] = append(alts[i], w)
			}
		}
	}
	elems := make([]string, len(alts))
	for i, a := range alts {
		if len(a) == 1 {
			elems[i] = starlarkString(a[0])
			continue
		}
		quoted := make([]string, len(a))
		for j, w := range a {
			quoted[j] = starlarkString(w)
		}
		elems[i] = "[" + strings.Join(quoted, ", ") + "]"
	}
	return "[" + strings.Join(elems, ", ") + "]"
}

// starlarkString quotes s as a Starlark string literal.
func starlarkString(s string) string {
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`).Replace(s) + `"`
}

// geminiPolicy is a Gemini CLI policy file. Rules match the whole command word by word with
// commandRegex, so `taskr list` never matches `taskr listall`; ask rules have the higher
// priority. In non-interactive mode Gemini CLI treats ask_user as deny.
func geminiPolicy(rules []permissionRule) []byte {
	var b strings.Builder
	b.WriteString("# Gemini CLI policy generated by rotini from the commands' effects. Copy this file to\n# ~/.gemini/policies/.\n")
	rule := func(re, decision string, priority int) {
		fmt.Fprintf(&b, "\n[[rule]]\ntoolName = \"run_shell_command\"\ncommandRegex = %s\ndecision = %q\npriority = %d\n", tomlString(re), decision, priority)
	}
	for _, r := range rules {
		prefix := wordsRegex(r)
		switch r.decision {
		case "allow":
			rule(prefix+`(\s|$)`, "allow", 100)
		case "ask":
			rule(prefix+`(\s|$)`, "ask_user", 200)
		}
		for _, id := range r.raising {
			rule(prefix+`\s(.*\s)?`+regexp.QuoteMeta(id)+`(\s|=|$)`, "ask_user", 200)
		}
	}
	return []byte(b.String())
}

// wordsRegex matches the start of a command line that runs the rule's command, by any of its
// spellings.
func wordsRegex(r permissionRule) string {
	alts := make([]string, len(r.spellings))
	for i, s := range r.spellings {
		words := strings.Fields(s)
		for j, w := range words {
			words[j] = regexp.QuoteMeta(w)
		}
		alts[i] = strings.Join(words, `\s+`)
	}
	if len(alts) == 1 {
		return "^" + alts[0]
	}
	return "^(" + strings.Join(alts, "|") + ")"
}

// tomlString quotes s as a TOML basic string.
func tomlString(s string) string {
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, "\t", `\t`).Replace(s) + `"`
}
