// Code generated by rotini; DO NOT EDIT.
package rotini

import "github.com/go-rotini/rotini/rtk"

// Completion returns a shell-completion script for the program's
// spec. shell is one of [rtk.SupportedShells].
//
// Generated programs expose this as a thin wrapper so the
// `<program> completion <shell>` subcommand handler can call it
// without re-implementing per-shell formatting. The heavy lifting
// lives in rtk; the program-specific data comes from the embedded
// [Spec] value.
//
// Returns [rtk.ErrUnknownShell] for an unrecognized shell name.
func Completion(shell rtk.Shell) (string, error) {
	return rtk.GenerateCompletion(shell, Spec)
}
