// Code generated by rotini; DO NOT EDIT.
package rotini

import "github.com/go-rotini/rotini/rtk"

// RootFlags carries the root command's program-level flags. Each
// sub-command's Inputs type composes RootFlags so handlers see the
// inherited program scope alongside their own.
type RootFlags struct {
}

// RootInputs is the typed input for invocations of the root command
// (no sub-command supplied).
type RootInputs struct {
	Flags RootFlags
}

// RotiniCommandPath returns the empty string for the root command.
func (i *RootInputs) RotiniCommandPath() string { return "" }

// PopulateFromArgv reads parsed root-scope flag values into i.
func (i *RootInputs) PopulateFromArgv(r *rtk.Result) error {
	_ = r
	return nil
}

// CatFlags carries the "cat" command's own flags.
type CatFlags struct {
}

// CatArguments carries the "cat" command's positional arguments.
type CatArguments struct {
	Paths [][]string
}

// CatInputs is the typed input for the "cat" command.
// It composes the root program-level flags (RootFlags) plus the
// command's own flags and positional arguments. Intermediate-ancestor
// flag scopes are exposed under per-segment fields.
type CatInputs struct {
	RootFlags RootFlags
	Flags     CatFlags
	Arguments CatArguments
}

// RotiniCommandPath returns the hyphen-joined command path "cat".
func (i *CatInputs) RotiniCommandPath() string { return "cat" }

// PopulateFromArgv reads parsed flag and argument values into i.
func (i *CatInputs) PopulateFromArgv(r *rtk.Result) error {
	rtk.AssignVariadicStringArg(r.ParsedArgs, 0, &i.Arguments.Paths)
	_ = r
	return nil
}
