// Code generated by rotini; DO NOT EDIT.
package rotini

import "github.com/go-rotini/rotini/rtk"

// Spec is the resolved program specification. The rotini framework
// consults it to drive argv tokenization, env/config fallback, and
// validation before each handler runs. Regenerate by re-running
// `go tool rotini generate` against the project's .rotini.spec.yaml.
var Spec = rtk.ProgramSpec{
	Name: "cat",
	Commands: []rtk.CommandSpec{
		{
			Path: "cat",
			Name: "cat",
			Arguments: []rtk.ArgumentSpec{
				{Name: "paths", Type: "[]string", Required: true, Variadic: true},
			},
		},
	},
}
