# yaml-language-server: $schema=./.rotini-schema.conf.json
version: 0.0.0
generate:
  schemas:
    spec:
      path: cmd/rotini/.rotini-schema.spec.json
    conf:
      path: cmd/rotini/.rotini-schema.conf.json
  packages:
    - type: main
      file: cmd/rotini/main.go
      package: main
    - type: cmd
      file: internal/cmd/rotini/zz_rotini.go
      package: rotini
    - type: runtime
      file: internal/rotini/zz_rotini.go
      package: rotini
  features:
    - type: help
      enabled: true
      embed: false
      embed_dir: internal/cmd/rotini/renders
      template: false
      template_dir: internal/cmd/rotini/templates
    - type: completion
      enabled: false
      embed: false
      embed_dir: internal/cmd/rotini/renders
      template: false
      template_dir: internal/cmd/rotini/templates
    - type: man
      enabled: false
      embed: false
      embed_dir: internal/cmd/rotini/renders
      template: false
      template_dir: internal/cmd/rotini/templates
    - type: markdown
      enabled: false
      embed: false
      embed_dir: internal/cmd/rotini/renders
      template: false
      template_dir: internal/cmd/rotini/templates
validate:
  fail: collect
