$schema: https://raw.githubusercontent.com/go-rotini/rotini/refs/tags/0.0.0/schema-conf.json
initialize:
  package: cmd
  format: yaml
generate:
  packages:
    entrypoint:
      package: cmd/rotini
      file: main.go
    cmd:
      package: internal/cmd/rotini
      file: zz_rotini.gen.go
    cmdgen:
      package: internal/cmd/rotini
      file: zz_rotini.gen.go
  features:
    help:
      enabled: true
      dir: internal/cmd/rotini/embed
    man:
      enabled: true
      dir: internal/cmd/rotini/embed
    completion:
      enabled: true
      dir: internal/cmd/rotini/embed
validate:
  fail: collect
