// Code generated by rotini; DO NOT EDIT.
package acme

import (
	_ "embed"
	"fmt"
	"strings"

	"github.com/go-rotini/rotini"
)

type handlers struct{}

var _ ProgramHandlers = (*handlers)(nil)

var Program = NewProgram(&handlers{})

func Handlers() ProgramHandlers {
	return &handlers{}
}

func (*handlers) Acme() rotini.CommandHandlers {
	return &acmeHandlers{}
}

func (*handlers) AcmeDeploy() rotini.CommandHandlers {
	return &acmeDeployHandlers{}
}

func (*handlers) AcmeVersion() rotini.CommandHandlers {
	return &acmeVersionHandlers{}
}

type ProgramHandlers interface {
	Acme() rotini.CommandHandlers
	AcmeDeploy() rotini.CommandHandlers
	AcmeVersion() rotini.CommandHandlers
}

var definition = rotini.Definition{
	Name:    "acme",
	Handler: "Acme",
	Flags: []rotini.FlagDef{
		{Name: "help", Identifiers: []string{"-h", "--help"}, Summary: "print help", Type: "bool"},
		{Name: "version", Identifiers: []string{"-v", "--version"}, Summary: "print version", Type: "bool"},
	},
	Commands: []rotini.CommandDef{
		{Name: "deploy",
			Handler: "AcmeDeploy",
			Summary: "deploy a service",
			Flags: []rotini.FlagDef{
				{Name: "env", Identifiers: []string{"--env", "-e"}, Summary: "target environment", Type: "string", Default: "dev", Enum: []string{"dev", "staging", "prod"}},
				{Name: "replicas", Identifiers: []string{"--replicas"}, Summary: "desired replica count", Type: "int", Default: "1", Constraints: rotini.Constraints{Minimum: 1, Maximum: 10}},
				{Name: "dry-run", Identifiers: []string{"--dry-run"}, Summary: "print the plan without applying it", Type: "bool"},
				{Name: "loud", Identifiers: []string{"--loud", "-l"}, Summary: "crank up verbosity, per occurrence", Type: "count"},
				{Name: "explain", Identifiers: []string{"--explain"}, Summary: "show where every reconciled value came from", Type: "bool"},
			},
			Arguments: []rotini.ArgDef{
				{Name: "service", Type: "string", Required: true},
			},
		},
		{Name: "version",
			Handler: "AcmeVersion",
			Summary: "print version",
			Flags: []rotini.FlagDef{
				{Name: "help", Identifiers: []string{"-h", "--help"}, Summary: "print help", Type: "bool"},
			},
		},
	},
}

type AcmeFlags struct {
	Help    bool `rotini:"help"`
	Version bool `rotini:"version"`
}

type AcmeArguments struct{}

type AcmeCommandInputs struct {
	Flags     AcmeFlags
	Arguments AcmeArguments
}

type AcmeInputs struct {
	Acme AcmeCommandInputs
}

type AcmeDeployFlags struct {
	Env      string `rotini:"env" recon:"deploy.env"`
	Replicas int    `rotini:"replicas"`
	DryRun   bool   `rotini:"dry-run"`
	Loud     int    `rotini:"loud"`
	Explain  bool   `rotini:"explain"`
}

type AcmeDeployArguments struct {
	Service string `rotini:"service"`
}

type AcmeDeployEnv struct {
	Region string `rotini:"region" recon:"region"`
}

type AcmeDeployCommandInputs struct {
	Flags     AcmeDeployFlags
	Arguments AcmeDeployArguments
	Env       AcmeDeployEnv
}

type AcmeDeployInputs struct {
	Acme       AcmeCommandInputs
	AcmeDeploy AcmeDeployCommandInputs
}

type AcmeVersionFlags struct {
	Help bool `rotini:"help"`
}

type AcmeVersionArguments struct{}

type AcmeVersionCommandInputs struct {
	Flags     AcmeVersionFlags
	Arguments AcmeVersionArguments
}

type AcmeVersionInputs struct {
	Acme        AcmeCommandInputs
	AcmeVersion AcmeVersionCommandInputs
}

// BindMeta is the generated descriptor the default binder (rotini.Binder) consumes.
var BindMeta = rotini.BindMeta{
	EnvPrefix: "ACME",
	ConfigFiles: []rotini.ConfigFile{
		{Name: "project", Format: "yaml", Discover: &rotini.DiscoverDef{Strategy: "walk-up", File: ".acme.yaml"}},
	},
}

// NewProgram builds the program from the generated command tree and the typed
// ProgramHandlers, delegating to rotini.NewProgram (which takes the handlers
// as an untyped value). Construct your program with this so the compiler verifies
// your handlers satisfy ProgramHandlers. The command tree is an unexported
// implementation detail — you hold a *rotini.Program, never the Definition.
func NewProgram(handlers ProgramHandlers) *rotini.Program {
	return rotini.NewProgram(definition, handlers)
}

//go:embed embed/help_acme.txt
var HelpAcme string

//go:embed embed/help_acme_deploy.txt
var HelpAcmeDeploy string

//go:embed embed/help_acme_version.txt
var HelpAcmeVersion string

// Help returns the generated help text for the command identified by path
// (command names or aliases; no arguments for the root command). It returns an
// error when path does not match a known command.
func Help(path ...string) (string, error) {
	switch strings.Join(path, " ") {
	case "":
		return HelpAcme, nil
	case "deploy":
		return HelpAcmeDeploy, nil
	case "version":
		return HelpAcmeVersion, nil
	default:
		return "", fmt.Errorf("no help for command %q", strings.Join(path, " "))
	}
}
