// Code generated by rotini; DO NOT EDIT.
package handlers

import (
	"github.com/go-rotini/rotini"
	"github.com/go-rotini/rotini/cmd/rotini/gen"
)

type handlers struct{}

var _ gen.ProgramHandlers = (*handlers)(nil)

var Program = rotini.NewProgram(&handlers{})

func (*handlers) Rotini() rotini.CommandHandlers {
	return &rotiniHandlers{}
}

func (*handlers) RotiniCompletion() rotini.CommandHandlers {
	return &rotiniCompletionHandlers{}
}

func (*handlers) RotiniGenerate() rotini.CommandHandlers {
	return &rotiniGenerateHandlers{}
}

func (*handlers) RotiniHelp() rotini.CommandHandlers {
	return &rotiniHelpHandlers{}
}

func (*handlers) RotiniInitialize() rotini.CommandHandlers {
	return &rotiniInitializeHandlers{}
}

func (*handlers) RotiniValidate() rotini.CommandHandlers {
	return &rotiniValidateHandlers{}
}

func (*handlers) RotiniVersion() rotini.CommandHandlers {
	return &rotiniVersionHandlers{}
}
