// Code generated by rotini; DO NOT EDIT.
package rotini

import "github.com/go-rotini/rotini/rtk"

// RootFlags carries the root command's program-level flags. Each
// sub-command's Inputs type composes RootFlags so handlers see the
// inherited program scope alongside their own.
type RootFlags struct {
	Verbose bool
}

// RootInputs is the typed input for invocations of the root command
// (no sub-command supplied).
type RootInputs struct {
	Flags RootFlags
}

// RotiniCommandPath returns the empty string for the root command.
func (i *RootInputs) RotiniCommandPath() string { return "" }

// PopulateFromArgv reads parsed root-scope flag values into i.
func (i *RootInputs) PopulateFromArgv(r *rtk.Result) error {
	if scope := r.FlagsByScope[""]; scope != nil {
		rtk.AssignFlag(scope, "verbose", &i.Flags.Verbose)
	}
	_ = r
	return nil
}

// FooFlags carries the "foo" command's own flags.
type FooFlags struct {
	Fopt string
}

// FooInputs is the typed input for the "foo" command.
// It composes the root program-level flags (RootFlags) plus the
// command's own flags and positional arguments. Intermediate-ancestor
// flag scopes are exposed under per-segment fields.
type FooInputs struct {
	RootFlags RootFlags
	Flags     FooFlags
}

// RotiniCommandPath returns the hyphen-joined command path "foo".
func (i *FooInputs) RotiniCommandPath() string { return "foo" }

// PopulateFromArgv reads parsed flag and argument values into i.
func (i *FooInputs) PopulateFromArgv(r *rtk.Result) error {
	if scope := r.FlagsByScope[""]; scope != nil {
		rtk.AssignFlag(scope, "verbose", &i.RootFlags.Verbose)
	}
	if scope := r.FlagsByScope["foo"]; scope != nil {
		rtk.AssignFlag(scope, "fopt", &i.Flags.Fopt)
	}
	_ = r
	return nil
}

// FooBarFlags carries the "foo-bar" command's own flags.
type FooBarFlags struct {
	Bopt int
}

// FooBarInputs is the typed input for the "foo-bar" command.
// It composes the root program-level flags (RootFlags) plus the
// command's own flags and positional arguments. Intermediate-ancestor
// flag scopes are exposed under per-segment fields.
type FooBarInputs struct {
	RootFlags RootFlags
	FooFlags  FooFlags
	Flags     FooBarFlags
}

// RotiniCommandPath returns the hyphen-joined command path "foo-bar".
func (i *FooBarInputs) RotiniCommandPath() string { return "foo-bar" }

// PopulateFromArgv reads parsed flag and argument values into i.
func (i *FooBarInputs) PopulateFromArgv(r *rtk.Result) error {
	if scope := r.FlagsByScope[""]; scope != nil {
		rtk.AssignFlag(scope, "verbose", &i.RootFlags.Verbose)
	}
	if scope := r.FlagsByScope["foo"]; scope != nil {
		rtk.AssignFlag(scope, "fopt", &i.FooFlags.Fopt)
	}
	if scope := r.FlagsByScope["bar"]; scope != nil {
		rtk.AssignFlag(scope, "bopt", &i.Flags.Bopt)
	}
	_ = r
	return nil
}

// FooBarBazFlags carries the "foo-bar-baz" command's own flags.
type FooBarBazFlags struct {
	Zopt string
}

// FooBarBazInputs is the typed input for the "foo-bar-baz" command.
// It composes the root program-level flags (RootFlags) plus the
// command's own flags and positional arguments. Intermediate-ancestor
// flag scopes are exposed under per-segment fields.
type FooBarBazInputs struct {
	RootFlags   RootFlags
	FooFlags    FooFlags
	FooBarFlags FooBarFlags
	Flags       FooBarBazFlags
}

// RotiniCommandPath returns the hyphen-joined command path "foo-bar-baz".
func (i *FooBarBazInputs) RotiniCommandPath() string { return "foo-bar-baz" }

// PopulateFromArgv reads parsed flag and argument values into i.
func (i *FooBarBazInputs) PopulateFromArgv(r *rtk.Result) error {
	if scope := r.FlagsByScope[""]; scope != nil {
		rtk.AssignFlag(scope, "verbose", &i.RootFlags.Verbose)
	}
	if scope := r.FlagsByScope["foo"]; scope != nil {
		rtk.AssignFlag(scope, "fopt", &i.FooFlags.Fopt)
	}
	if scope := r.FlagsByScope["bar"]; scope != nil {
		rtk.AssignFlag(scope, "bopt", &i.FooBarFlags.Bopt)
	}
	if scope := r.FlagsByScope["baz"]; scope != nil {
		rtk.AssignFlag(scope, "zopt", &i.Flags.Zopt)
	}
	_ = r
	return nil
}
