// Code generated by rotini; DO NOT EDIT.
package rotini

import "github.com/go-rotini/rotini/rtk"

// Spec is the resolved program specification. The rotini framework
// consults it to drive argv tokenization, env/config fallback, and
// validation before each handler runs. Regenerate by re-running
// `go tool rotini generate` against the project's .rotini.spec.yaml.
var Spec = rtk.ProgramSpec{
	Name: "myprog",
	Flags: []rtk.FlagSpec{
		{Name: "verbose", Identifiers: []string{"-v", "--verbose"}, Type: "bool"},
	},
	Commands: []rtk.CommandSpec{
		{
			Path: "foo",
			Name: "foo",
			Flags: []rtk.FlagSpec{
				{Name: "fopt", Identifiers: []string{"--fopt"}, Type: "string"},
			},
			Commands: []rtk.CommandSpec{
				{
					Path: "foo-bar",
					Name: "bar",
					Flags: []rtk.FlagSpec{
						{Name: "bopt", Identifiers: []string{"--bopt"}, Type: "int"},
					},
					Commands: []rtk.CommandSpec{
						{
							Path: "foo-bar-baz",
							Name: "baz",
							Flags: []rtk.FlagSpec{
								{Name: "zopt", Identifiers: []string{"--zopt"}, Type: "string"},
							},
						},
					},
				},
			},
		},
	},
}
