$schema: https://raw.githubusercontent.com/go-rotini/rotini/refs/tags/0.0.0/schema-conf.json
generate:
  packages:
    entrypoint:
      package: examples/acme
      file: main.go
    cmd:
      package: examples/acme/internal/acme
      file: zz_rotini.gen.go
    cmdgen:
      package: examples/acme/internal/acme
      file: zz_rotini.gen.go
  features:
    help:
      enabled: true
      dir: examples/acme/internal/acme/embed
