.TH "OPS\-UPPER" 1 "" "ops" "User Commands"
.SH NAME
ops\-upper \- upper\-case lines
.SH SYNOPSIS
\fBops upper\fR
.SH "GLOBAL OPTIONS"
.TP
\fB\-h\fR, \fB\-\-help\fR
print help
.TP
\fB\-v\fR, \fB\-\-verbose\fR
say more (repeatable)
.br
repeat to count: \-vvv
.TP
\fB\-\-color\fR \fIstring\fR
when to color (default auto) [auto|always|never]
.SH STDIN
Reads lines of text from standard input.
.SH "SEE ALSO"
\fBops\fR(1)
