// Code generated by rotini; DO NOT EDIT.
package rotini

import "github.com/go-rotini/rotini/rtk"

// executors is the per-command-path dispatch map. [Program.Execute]
// looks up the matched command path and invokes the resulting
// [Execution] under [SafeCall].
//
// Every entry corresponds to a node in the user's spec tree; the
// root command is keyed by the empty string.
var executors = map[string]func(*Program) Execution{
	"":       buildRootExecution,
	"list":   buildListExecution,
	"remove": buildRemoveExecution,
}

// buildRootExecution builds the [Execution] for the root command. It
// parses the typed RootInputs from the bound parser and invokes the
// handler returned by Handlers.Root().
func buildRootExecution(p *Program) Execution {
	return Execution{
		Path: "",
		Run: func() error {
			parser := rtk.Get[rtk.Parser](p.registry, "parser")
			if parser == nil {
				return ErrParserUnbound
			}
			var inputs RootInputs
			if err := parser.Parse(&inputs); err != nil {
				return err
			}
			return p.handlers.Root().Run(rtk.Ctx{Registry: p.registry}, &inputs)
		},
	}
}

// buildListExecution builds the [Execution] for the
// "list" command.
func buildListExecution(p *Program) Execution {
	return Execution{
		Path: "list",
		Run: func() error {
			parser := rtk.Get[rtk.Parser](p.registry, "parser")
			if parser == nil {
				return ErrParserUnbound
			}
			var inputs ListInputs
			if err := parser.Parse(&inputs); err != nil {
				return err
			}
			return p.handlers.List().Run(rtk.Ctx{Registry: p.registry}, &inputs)
		},
	}
}

// buildRemoveExecution builds the [Execution] for the
// "remove" command.
func buildRemoveExecution(p *Program) Execution {
	return Execution{
		Path: "remove",
		Run: func() error {
			parser := rtk.Get[rtk.Parser](p.registry, "parser")
			if parser == nil {
				return ErrParserUnbound
			}
			var inputs RemoveInputs
			if err := parser.Parse(&inputs); err != nil {
				return err
			}
			return p.handlers.Remove().Run(rtk.Ctx{Registry: p.registry}, &inputs)
		},
	}
}
