// Code generated by rotini; DO NOT EDIT.
package rotini

import "github.com/go-rotini/rotini/rtk"

// RootFlags carries the root command's program-level flags. Each
// sub-command's Inputs type composes RootFlags so handlers see the
// inherited program scope alongside their own.
type RootFlags struct {
}

// RootInputs is the typed input for invocations of the root command
// (no sub-command supplied).
type RootInputs struct {
	Flags RootFlags
}

// RotiniCommandPath returns the empty string for the root command.
func (i *RootInputs) RotiniCommandPath() string { return "" }

// PopulateFromArgv reads parsed root-scope flag values into i.
func (i *RootInputs) PopulateFromArgv(r *rtk.Result) error {
	_ = r
	return nil
}

// ListFlags carries the "list" command's own flags.
type ListFlags struct {
}

// ListInputs is the typed input for the "list" command.
// It composes the root program-level flags (RootFlags) plus the
// command's own flags and positional arguments. Intermediate-ancestor
// flag scopes are exposed under per-segment fields.
type ListInputs struct {
	RootFlags RootFlags
	Flags     ListFlags
}

// RotiniCommandPath returns the hyphen-joined command path "list".
func (i *ListInputs) RotiniCommandPath() string { return "list" }

// PopulateFromArgv reads parsed flag and argument values into i.
func (i *ListInputs) PopulateFromArgv(r *rtk.Result) error {
	_ = r
	return nil
}

// RemoveFlags carries the "remove" command's own flags.
type RemoveFlags struct {
}

// RemoveInputs is the typed input for the "remove" command.
// It composes the root program-level flags (RootFlags) plus the
// command's own flags and positional arguments. Intermediate-ancestor
// flag scopes are exposed under per-segment fields.
type RemoveInputs struct {
	RootFlags RootFlags
	Flags     RemoveFlags
}

// RotiniCommandPath returns the hyphen-joined command path "remove".
func (i *RemoveInputs) RotiniCommandPath() string { return "remove" }

// PopulateFromArgv reads parsed flag and argument values into i.
func (i *RemoveInputs) PopulateFromArgv(r *rtk.Result) error {
	_ = r
	return nil
}
