// Code generated by rotini; DO NOT EDIT.
package rotini

import (
	"fmt"
	"strings"

	"github.com/go-rotini/rotini/internal/rotini"
)

type ProgramHandlers interface {
	Rotini() rotini.Handlers
	RotiniGenerate() rotini.Handlers
	RotiniHelp() rotini.Handlers
	RotiniInitialize() rotini.Handlers
	RotiniValidate() rotini.Handlers
	RotiniVersion() rotini.Handlers
}

var definition = rotini.Definition{
	Name:    "rotini",
	Handler: "Rotini",
	Flags: []rotini.FlagDef{
		{Name: "nostyles", Identifiers: []string{"--no-styles"}, Summary: "disable output styles", Type: "bool"},
		{Name: "version", Identifiers: []string{"-v", "--version"}, Summary: "print version", Type: "bool"},
		{Name: "help", Identifiers: []string{"-h", "--help"}, Summary: "print help", Type: "bool"},
	},
	Commands: []rotini.CommandDef{
		{Name: "initialize",
			Handler: "RotiniInitialize",
			Summary: "scaffold a cli program",
			Aliases: []string{"init"},
			Flags: []rotini.FlagDef{
				{Name: "format", Identifiers: []string{"--format"}, Summary: "the created rotini spec file format (defaults to the module conf's initialize.format, else yaml)", Type: "string", Enum: []string{"yaml", "json", "jsonc", "toml"}},
				{Name: "force", Identifiers: []string{"--force"}, Summary: "force re-initialization if files exist that init would overwrite", Type: "bool"},
				{Name: "help", Identifiers: []string{"-h", "--help"}, Summary: "print help", Type: "bool"},
			},
			Arguments: []rotini.ArgDef{
				{Name: "name", Type: "string"},
			},
		},
		{Name: "generate",
			Handler: "RotiniGenerate",
			Summary: "generate a cli program",
			Aliases: []string{"gen"},
			Flags: []rotini.FlagDef{
				{Name: "conf_file_path", Identifiers: []string{"-c", "--config"}, Summary: "path to the rotini conf file", Type: "string", Default: ".rotini.conf.yaml"},
				{Name: "watch", Identifiers: []string{"--watch", "-w"}, Summary: "watch a rotini spec file for changes and re-generate", Type: "bool"},
				{Name: "help", Identifiers: []string{"-h", "--help"}, Summary: "print help", Type: "bool"},
			},
			Arguments: []rotini.ArgDef{
				{Name: "spec_file_path", Type: "string", Default: ".rotini.spec.yaml"},
			},
		},
		{Name: "validate",
			Handler: "RotiniValidate",
			Summary: "validate a spec file",
			Aliases: []string{"val"},
			Flags: []rotini.FlagDef{
				{Name: "conf_file_path", Identifiers: []string{"-c", "--config"}, Summary: "path to the rotini conf file", Type: "string", Default: ".rotini.conf.yaml"},
				{Name: "fail", Identifiers: []string{"--fail"}, Summary: "failure reporting — fast (first problem) or collect (all); defaults to the module conf's validate.fail, else collect", Type: "string", Enum: []string{"fast", "collect"}},
				{Name: "watch", Identifiers: []string{"--watch", "-w"}, Summary: "watch a rotini spec file for changes and re-generate", Type: "bool"},
				{Name: "help", Identifiers: []string{"-h", "--help"}, Summary: "print help", Type: "bool"},
			},
			Arguments: []rotini.ArgDef{
				{Name: "spec_file_path", Type: "string", Default: ".rotini.spec.yaml"},
			},
		},
		{Name: "help",
			Handler: "RotiniHelp",
			Summary: "print help",
			Flags: []rotini.FlagDef{
				{Name: "help", Identifiers: []string{"-h", "--help"}, Summary: "print help", Type: "bool"},
			},
			Arguments: []rotini.ArgDef{
				{Name: "command", Type: "[]string", Variadic: true},
			},
		},
		{Name: "version",
			Handler: "RotiniVersion",
			Summary: "print version",
			Flags: []rotini.FlagDef{
				{Name: "help", Identifiers: []string{"-h", "--help"}, Summary: "print help", Type: "bool"},
			},
		},
	},
}

type RotiniFlags struct {
	Nostyles bool `rotini:"nostyles"`
	Version  bool `rotini:"version"`
	Help     bool `rotini:"help"`
}

type RotiniArguments struct{}

type RotiniEnv struct {
	Nostyles bool `rotini:"nostyles" recon:"nostyles" env:"ROTINI_NO_STYLES"`
	Ci       bool `rotini:"ci" recon:"ci" env:"CI"`
}

type RotiniCommandInputs struct {
	Flags     RotiniFlags
	Arguments RotiniArguments
	Env       RotiniEnv
}

type RotiniInputs struct {
	Rotini RotiniCommandInputs
}

type RotiniGenerateFlags struct {
	ConfFilePath string `rotini:"conf_file_path"`
	Watch        bool   `rotini:"watch"`
	Help         bool   `rotini:"help"`
}

type RotiniGenerateArguments struct {
	SpecFilePath string `rotini:"spec_file_path"`
}

type RotiniGenerateCommandInputs struct {
	Flags     RotiniGenerateFlags
	Arguments RotiniGenerateArguments
}

type RotiniGenerateInputs struct {
	Rotini         RotiniCommandInputs
	RotiniGenerate RotiniGenerateCommandInputs
}

type RotiniHelpFlags struct {
	Help bool `rotini:"help"`
}

type RotiniHelpArguments struct {
	Command []string `rotini:"command"`
}

type RotiniHelpCommandInputs struct {
	Flags     RotiniHelpFlags
	Arguments RotiniHelpArguments
}

type RotiniHelpInputs struct {
	Rotini     RotiniCommandInputs
	RotiniHelp RotiniHelpCommandInputs
}

type RotiniInitializeFlags struct {
	Format string `rotini:"format"`
	Force  bool   `rotini:"force"`
	Help   bool   `rotini:"help"`
}

type RotiniInitializeArguments struct {
	Name string `rotini:"name"`
}

type RotiniInitializeCommandInputs struct {
	Flags     RotiniInitializeFlags
	Arguments RotiniInitializeArguments
}

type RotiniInitializeInputs struct {
	Rotini           RotiniCommandInputs
	RotiniInitialize RotiniInitializeCommandInputs
}

type RotiniValidateFlags struct {
	ConfFilePath string `rotini:"conf_file_path"`
	Fail         string `rotini:"fail"`
	Watch        bool   `rotini:"watch"`
	Help         bool   `rotini:"help"`
}

type RotiniValidateArguments struct {
	SpecFilePath string `rotini:"spec_file_path"`
}

type RotiniValidateCommandInputs struct {
	Flags     RotiniValidateFlags
	Arguments RotiniValidateArguments
}

type RotiniValidateInputs struct {
	Rotini         RotiniCommandInputs
	RotiniValidate RotiniValidateCommandInputs
}

type RotiniVersionFlags struct {
	Help bool `rotini:"help"`
}

type RotiniVersionArguments struct{}

type RotiniVersionCommandInputs struct {
	Flags     RotiniVersionFlags
	Arguments RotiniVersionArguments
}

type RotiniVersionInputs struct {
	Rotini        RotiniCommandInputs
	RotiniVersion RotiniVersionCommandInputs
}

// BindMeta is the generated descriptor the default binder (rotini.Binder) consumes.
var BindMeta = rotini.BindMeta{}

// NewProgram builds the program from the generated command tree and the typed
// ProgramHandlers, delegating to rotini.NewProgram (which takes the handlers
// as an untyped value). Construct your program with this so the compiler verifies
// your handlers satisfy ProgramHandlers. The command tree is an unexported
// implementation detail — you hold a *rotini.Program, never the Definition.
func NewProgram(handlers ProgramHandlers) *rotini.Program {
	// BindMeta rides the registry so the per-channel input functions
	// (rotini.ParseEnv, rotini.ParseFiles, …) need only the Context.
	return rotini.NewProgram(definition, handlers).
		Bind(rotini.KeyBindMeta, BindMeta)
}

// handlers is the generated ProgramHandlers implementation: each method wires a
// command to its handler (an own command's local handler type, or a composed
// command's delegated package). Program is the ready-to-run program; Handlers()
// returns a fresh value (e.g. for tests).
type handlers struct{}

var _ ProgramHandlers = (*handlers)(nil)

var Program = NewProgram(&handlers{})

func Handlers() ProgramHandlers {
	return &handlers{}
}

func (*handlers) Rotini() rotini.Handlers {
	return &rotiniHandlers{}
}

func (*handlers) RotiniGenerate() rotini.Handlers {
	return &rotiniGenerateHandlers{}
}

func (*handlers) RotiniHelp() rotini.Handlers {
	return &rotiniHelpHandlers{}
}

func (*handlers) RotiniInitialize() rotini.Handlers {
	return &rotiniInitializeHandlers{}
}

func (*handlers) RotiniValidate() rotini.Handlers {
	return &rotiniValidateHandlers{}
}

func (*handlers) RotiniVersion() rotini.Handlers {
	return &rotiniVersionHandlers{}
}

var HelpRotini = "The rotini cli framework companion cli.\n\nFind more information at: https://rotini.dev\n\nUsage:\n  rotini <command> <arguments> [flags]\n        [-v | --version] [-h | --help]\n\nCommands:\n  initialize;init    scaffold a cli program\n  generate;gen       generate a cli program\n  validate;val       validate a spec file\n  help               print help\n  version            print version\n\nFlags:\n  --no-styles     disable output styles\n  -v,--version    print version\n  -h,--help       print help\n\nEnvironment:\n  ROTINI_NO_STYLES    disable output styles\n  CI                  is cli environment\n\nExamples:\n  rotini init mycli\n  rotini validate .rotini.spec.yaml\n  rotini generate ./path/to/.rotini.spec.json\n\nUse \"rotini help <command>\" for more information about a command."

var HelpRotiniInitialize = "Scaffold a new rotini CLI — write the spec + conf, then run the first generate (entrypoint, empty handler stubs, codegen) so it is ready to build.\n\nUsage:\n  rotini initialize [name] [flags]\n\nArguments:\n  [name]    the root command name written to the created spec file (expected binary name)\n\nFlags:\n  --format string    the created rotini spec file format (defaults to the module conf's initialize.format, else yaml) [yaml|json|jsonc|toml]\n  --force            force re-initialization if files exist that init would overwrite\n  -h,--help          print help\n\nExamples:\n  rotini initialize mycli\n  rotini init mycli --format json\n  rotini init mycli --force\n\nUse \"rotini help <command>\" for more information about a command."

var HelpRotiniGenerate = "Generate a cli program from a rotini spec file.\n\nUsage:\n  rotini generate [spec_file_path] [flags]\n\nArguments:\n  [spec_file_path]    path to the spec file (default .rotini.spec.yaml)\n\nFlags:\n  -c,--config string    path to the rotini conf file (default .rotini.conf.yaml)\n  --watch,-w            watch a rotini spec file for changes and re-generate\n  -h,--help             print help\n\nExamples:\n  rotini generate\n  rotini generate ./path/to/.rotini.json --watch\n\nUse \"rotini help <command>\" for more information about a command."

var HelpRotiniValidate = "Validate a rotini spec file for correctness.\n\nUsage:\n  rotini validate [spec_file_path] [flags]\n\nArguments:\n  [spec_file_path]    path to the spec file (default .rotini.spec.yaml)\n\nFlags:\n  -c,--config string    path to the rotini conf file (default .rotini.conf.yaml)\n  --fail string         failure reporting — fast (first problem) or collect (all); defaults to the module conf's validate.fail, else collect [fast|collect]\n  --watch,-w            watch a rotini spec file for changes and re-generate\n  -h,--help             print help\n\nExamples:\n  rotini validate\n  rotini val ./path/to/.rotini.yaml\n\nUse \"rotini help <command>\" for more information about a command."

var HelpRotiniHelp = "Print help for a specific command.\n\nUsage:\n  rotini help [command...] [flags]\n\nArguments:\n  [command...]    name of the command to print help for\n\nFlags:\n  -h,--help    print help\n\nExamples:\n  rotini help\n  rotini help generate\n  rotini help init\n\nUse \"rotini help <command>\" for more information about a command."

var HelpRotiniVersion = "Print the rotini cli version.\n\nUsage:\n  rotini version [flags]\n\nFlags:\n  -h,--help    print help\n\nExamples:\n  rotini version\n\nUse \"rotini help <command>\" for more information about a command."

// Help returns the generated help text for the command identified by path
// (command names or aliases; no arguments for the root command). It returns an
// error when path does not match a known command.
func Help(path ...string) (string, error) {
	switch strings.Join(path, " ") {
	case "":
		return HelpRotini, nil
	case "initialize", "init":
		return HelpRotiniInitialize, nil
	case "generate", "gen":
		return HelpRotiniGenerate, nil
	case "validate", "val":
		return HelpRotiniValidate, nil
	case "help":
		return HelpRotiniHelp, nil
	case "version":
		return HelpRotiniVersion, nil
	default:
		return "", fmt.Errorf("no help for command %q", strings.Join(path, " "))
	}
}

var CompletionBash = "# bash completion for rotini\n# Candidates arrive as \"name<TAB>description\"; bash cannot render descriptions,\n# so everything from the first tab is stripped.\n_rotini_complete() {\n    local args line IFS=$'\\n'\n    args=(\"${COMP_WORDS[@]:1:$COMP_CWORD}\")\n    COMPREPLY=()\n    for line in $(rotini __complete \"${args[@]}\" 2>/dev/null); do\n        COMPREPLY+=(\"${line%%$'\\t'*}\")\n    done\n}\ncomplete -o default -F _rotini_complete rotini\n"

var CompletionZsh = "#compdef rotini\n# Candidates arrive as \"name<TAB>description\"; zsh renders the description\n# beside the name via _describe (colons in either part are escaped).\n_rotini() {\n    local -a lines pairs\n    local line name desc\n    lines=(${(f)\"$(rotini __complete ${words[2,$CURRENT]} 2>/dev/null)\"})\n    for line in $lines; do\n        if [[ $line == *$'\\t'* ]]; then\n            name=${line%%$'\\t'*}\n            desc=${line#*$'\\t'}\n            pairs+=(\"${name//:/\\\\:}:${desc//:/\\\\:}\")\n        else\n            pairs+=(\"${line//:/\\\\:}\")\n        fi\n    done\n    _describe 'rotini' pairs\n}\ncompdef _rotini rotini\n"

var CompletionFish = "# fish completion for rotini\nfunction __rotini_complete\n    set -l tokens (commandline -opc) (commandline -ct)\n    rotini __complete $tokens[2..-1] 2>/dev/null\nend\n\nfunction __rotini_has_results\n    set -g __rotini_results (__rotini_complete)\n    test (count $__rotini_results) -gt 0\nend\n\n# Offer the binary's candidates when it has any; otherwise fall back to fish's\n# file completion (the binary returns nothing for path-valued flags and\n# arguments, exactly so the shell takes over). Candidates arrive as\n# \"name<TAB>description\" — fish renders that shape natively.\ncomplete -c rotini -f -n '__rotini_has_results' -a '$__rotini_results'\ncomplete -c rotini -F -n 'not __rotini_has_results'\n"

var CompletionPowershell = "# PowerShell completion for rotini\nRegister-ArgumentCompleter -Native -CommandName rotini -ScriptBlock {\n    param($wordToComplete, $commandAst, $cursorPosition)\n    $tokens = @($commandAst.CommandElements | Select-Object -Skip 1 | ForEach-Object { $_.Extent.Text })\n    if ($wordToComplete -eq '') { $tokens += '' }\n    rotini __complete @tokens 2>$null | ForEach-Object {\n        # Candidates arrive as \"name<TAB>description\"; the description becomes\n        # the CompletionResult tooltip.\n        $parts = $_ -split \"`t\", 2\n        $text = $parts[0]\n        $tip = if ($parts.Count -gt 1 -and $parts[1]) { $parts[1] } else { $text }\n        [System.Management.Automation.CompletionResult]::new($text, $text, 'ParameterValue', $tip)\n    }\n}\n"

// Completion returns the embedded completion script for shell, or an error when
// shell is not one rotini generated a script for.
func Completion(shell string) (string, error) {
	switch shell {
	case "bash":
		return CompletionBash, nil
	case "zsh":
		return CompletionZsh, nil
	case "fish":
		return CompletionFish, nil
	case "powershell":
		return CompletionPowershell, nil
	default:
		return "", fmt.Errorf("no completion for shell %q", shell)
	}
}
