.TH "APP\-DEPLOY" 1 "" "app" "User Commands"
.SH NAME
app\-deploy \- deploy it
.SH SYNOPSIS
\fBapp deploy\fR [flags] <command> <target> [stage]
.SH DESCRIPTION
Effects: write, idempotent, open world
.SH "COMMANDS"
.TP
\fBcanary\fR
a canary deploy
.SH ARGUMENTS
.TP
\fI<target>\fR
what to deploy
.br
also set by \fBDEPLOY_TARGET\fR or config key \fBdeploy.target\fR
.TP
\fI[stage]\fR
which stage (default prod)
.SH "OPTIONS"
.TP
\fB\-r\fR, \fB\-\-replicas\fR \fIint\fR
how many (default 1)
.br
also set by \fBAPP_DEPLOY_REPLICAS\fR or config key \fBdeploy.replicas\fR
.TP
\fB\-\-region\fR \fIstring\fR
where
.br
also set by \fBDEPLOY_REGION\fR or config key \fBregion\fR
.TP
\fB\-\-prune\fR
remove old releases (destructive, not idempotent)
.SH "GLOBAL OPTIONS"
.TP
\fB\-\-verbose\fR
say more
.br
also set by \fBAPP_LOG_VERBOSE\fR or config key \fBlog.verbose\fR
.SH "SEE ALSO"
\fBapp\fR(1), \fBapp\-deploy\-canary\fR(1)
