// Code generated by rotini; DO NOT EDIT.
package rotini

import "github.com/go-rotini/rotini/rtk"

// executors is the per-command-path dispatch map. [Program.Execute]
// looks up the matched command path and invokes the resulting
// [Execution] under [SafeCall].
//
// Every entry corresponds to a node in the user's spec tree; the
// root command is keyed by the empty string.
var executors = map[string]func(*Program) Execution{
	"":           buildRootExecution,
	"completion": buildCompletionExecution,
	"generate":   buildGenerateExecution,
	"help":       buildHelpExecution,
	"initialize": buildInitializeExecution,
	"validate":   buildValidateExecution,
	"version":    buildVersionExecution,
}

// buildRootExecution builds the [Execution] for the root command. It
// parses the typed RootInputs from the bound parser and invokes the
// handler returned by Handlers.Root().
func buildRootExecution(p *Program) Execution {
	return Execution{
		Path: "",
		Run: func() error {
			parser := rtk.Get[rtk.Parser](p.registry, "parser")
			if parser == nil {
				return ErrParserUnbound
			}
			var inputs RootInputs
			if err := parser.Parse(&inputs); err != nil {
				return err
			}
			return p.handlers.Root().Run(rtk.Ctx{Registry: p.registry}, &inputs)
		},
	}
}

// buildCompletionExecution builds the [Execution] for the
// "completion" command.
func buildCompletionExecution(p *Program) Execution {
	return Execution{
		Path: "completion",
		Run: func() error {
			parser := rtk.Get[rtk.Parser](p.registry, "parser")
			if parser == nil {
				return ErrParserUnbound
			}
			var inputs CompletionInputs
			if err := parser.Parse(&inputs); err != nil {
				return err
			}
			return p.handlers.Completion().Run(rtk.Ctx{Registry: p.registry}, &inputs)
		},
	}
}

// buildGenerateExecution builds the [Execution] for the
// "generate" command.
func buildGenerateExecution(p *Program) Execution {
	return Execution{
		Path: "generate",
		Run: func() error {
			parser := rtk.Get[rtk.Parser](p.registry, "parser")
			if parser == nil {
				return ErrParserUnbound
			}
			var inputs GenerateInputs
			if err := parser.Parse(&inputs); err != nil {
				return err
			}
			return p.handlers.Generate().Run(rtk.Ctx{Registry: p.registry}, &inputs)
		},
	}
}

// buildHelpExecution builds the [Execution] for the
// "help" command.
func buildHelpExecution(p *Program) Execution {
	return Execution{
		Path: "help",
		Run: func() error {
			parser := rtk.Get[rtk.Parser](p.registry, "parser")
			if parser == nil {
				return ErrParserUnbound
			}
			var inputs HelpInputs
			if err := parser.Parse(&inputs); err != nil {
				return err
			}
			return p.handlers.Help().Run(rtk.Ctx{Registry: p.registry}, &inputs)
		},
	}
}

// buildInitializeExecution builds the [Execution] for the
// "initialize" command.
func buildInitializeExecution(p *Program) Execution {
	return Execution{
		Path: "initialize",
		Run: func() error {
			parser := rtk.Get[rtk.Parser](p.registry, "parser")
			if parser == nil {
				return ErrParserUnbound
			}
			var inputs InitializeInputs
			if err := parser.Parse(&inputs); err != nil {
				return err
			}
			return p.handlers.Initialize().Run(rtk.Ctx{Registry: p.registry}, &inputs)
		},
	}
}

// buildValidateExecution builds the [Execution] for the
// "validate" command.
func buildValidateExecution(p *Program) Execution {
	return Execution{
		Path: "validate",
		Run: func() error {
			parser := rtk.Get[rtk.Parser](p.registry, "parser")
			if parser == nil {
				return ErrParserUnbound
			}
			var inputs ValidateInputs
			if err := parser.Parse(&inputs); err != nil {
				return err
			}
			return p.handlers.Validate().Run(rtk.Ctx{Registry: p.registry}, &inputs)
		},
	}
}

// buildVersionExecution builds the [Execution] for the
// "version" command.
func buildVersionExecution(p *Program) Execution {
	return Execution{
		Path: "version",
		Run: func() error {
			parser := rtk.Get[rtk.Parser](p.registry, "parser")
			if parser == nil {
				return ErrParserUnbound
			}
			var inputs VersionInputs
			if err := parser.Parse(&inputs); err != nil {
				return err
			}
			return p.handlers.Version().Run(rtk.Ctx{Registry: p.registry}, &inputs)
		},
	}
}
