// Code generated by rotini; DO NOT EDIT.
package rotini

import "github.com/go-rotini/rotini/rtk"

// RootCtx is the [rtk.Ctx] alias for root-command handlers.
type RootCtx = rtk.Ctx

// RootHandler is the interface a root-command handler implementation
// satisfies. The framework calls Run after [RootInputs] has been
// populated from argv / env / config.
type RootHandler interface {
	Run(ctx RootCtx, inputs *RootInputs) error
}

// CompletionCtx is the [rtk.Ctx] alias for "completion" handlers.
type CompletionCtx = rtk.Ctx

// CompletionHandler is the interface a "completion" handler
// implementation satisfies.
type CompletionHandler interface {
	Run(ctx CompletionCtx, inputs *CompletionInputs) error
}

// GenerateCtx is the [rtk.Ctx] alias for "generate" handlers.
type GenerateCtx = rtk.Ctx

// GenerateHandler is the interface a "generate" handler
// implementation satisfies.
type GenerateHandler interface {
	Run(ctx GenerateCtx, inputs *GenerateInputs) error
}

// HelpCtx is the [rtk.Ctx] alias for "help" handlers.
type HelpCtx = rtk.Ctx

// HelpHandler is the interface a "help" handler
// implementation satisfies.
type HelpHandler interface {
	Run(ctx HelpCtx, inputs *HelpInputs) error
}

// InitializeCtx is the [rtk.Ctx] alias for "initialize" handlers.
type InitializeCtx = rtk.Ctx

// InitializeHandler is the interface a "initialize" handler
// implementation satisfies.
type InitializeHandler interface {
	Run(ctx InitializeCtx, inputs *InitializeInputs) error
}

// ValidateCtx is the [rtk.Ctx] alias for "validate" handlers.
type ValidateCtx = rtk.Ctx

// ValidateHandler is the interface a "validate" handler
// implementation satisfies.
type ValidateHandler interface {
	Run(ctx ValidateCtx, inputs *ValidateInputs) error
}

// VersionCtx is the [rtk.Ctx] alias for "version" handlers.
type VersionCtx = rtk.Ctx

// VersionHandler is the interface a "version" handler
// implementation satisfies.
type VersionHandler interface {
	Run(ctx VersionCtx, inputs *VersionInputs) error
}

// Handlers is the aggregate interface the user's handlers package
// satisfies. Each accessor returns the per-command handler the
// framework dispatches to. Codegen emits a default implementation in
// the user's `internal/handlers` package; users replace the bodies of
// the per-command Run methods to implement their CLI.
type Handlers interface {
	Root() RootHandler
	Completion() CompletionHandler
	Generate() GenerateHandler
	Help() HelpHandler
	Initialize() InitializeHandler
	Validate() ValidateHandler
	Version() VersionHandler
}
