// Code generated by rotini; DO NOT EDIT.
package rotini

import "github.com/go-rotini/rotini/rtk"

// RootFlags carries the root command's program-level flags. Each
// sub-command's Inputs type composes RootFlags so handlers see the
// inherited program scope alongside their own.
type RootFlags struct {
	Help    bool
	Version bool
}

// RootInputs is the typed input for invocations of the root command
// (no sub-command supplied).
type RootInputs struct {
	Flags RootFlags
}

// RotiniCommandPath returns the empty string for the root command.
func (i *RootInputs) RotiniCommandPath() string { return "" }

// PopulateFromArgv reads parsed root-scope flag values into i.
func (i *RootInputs) PopulateFromArgv(r *rtk.Result) error {
	if scope := r.FlagsByScope[""]; scope != nil {
		rtk.AssignFlag(scope, "help", &i.Flags.Help)
		rtk.AssignFlag(scope, "version", &i.Flags.Version)
	}
	_ = r
	return nil
}

// CompletionFlags carries the "completion" command's own flags.
type CompletionFlags struct {
	Help bool
}

// CompletionArguments carries the "completion" command's positional arguments.
type CompletionArguments struct {
	Shell string
}

// CompletionInputs is the typed input for the "completion" command.
// It composes the root program-level flags (RootFlags) plus the
// command's own flags and positional arguments. Intermediate-ancestor
// flag scopes are exposed under per-segment fields.
type CompletionInputs struct {
	RootFlags RootFlags
	Flags     CompletionFlags
	Arguments CompletionArguments
}

// RotiniCommandPath returns the hyphen-joined command path "completion".
func (i *CompletionInputs) RotiniCommandPath() string { return "completion" }

// PopulateFromArgv reads parsed flag and argument values into i.
func (i *CompletionInputs) PopulateFromArgv(r *rtk.Result) error {
	if scope := r.FlagsByScope[""]; scope != nil {
		rtk.AssignFlag(scope, "help", &i.RootFlags.Help)
		rtk.AssignFlag(scope, "version", &i.RootFlags.Version)
	}
	if scope := r.FlagsByScope["completion"]; scope != nil {
		rtk.AssignFlag(scope, "help", &i.Flags.Help)
	}
	rtk.AssignStringArg(r.ParsedArgs, 0, &i.Arguments.Shell)
	_ = r
	return nil
}

// GenerateFlags carries the "generate" command's own flags.
type GenerateFlags struct {
	Config string
	Help   bool
	Watch  bool
}

// GenerateArguments carries the "generate" command's positional arguments.
type GenerateArguments struct {
	File string
}

// GenerateInputs is the typed input for the "generate" command.
// It composes the root program-level flags (RootFlags) plus the
// command's own flags and positional arguments. Intermediate-ancestor
// flag scopes are exposed under per-segment fields.
type GenerateInputs struct {
	RootFlags RootFlags
	Flags     GenerateFlags
	Arguments GenerateArguments
}

// RotiniCommandPath returns the hyphen-joined command path "generate".
func (i *GenerateInputs) RotiniCommandPath() string { return "generate" }

// PopulateFromArgv reads parsed flag and argument values into i.
func (i *GenerateInputs) PopulateFromArgv(r *rtk.Result) error {
	if scope := r.FlagsByScope[""]; scope != nil {
		rtk.AssignFlag(scope, "help", &i.RootFlags.Help)
		rtk.AssignFlag(scope, "version", &i.RootFlags.Version)
	}
	if scope := r.FlagsByScope["generate"]; scope != nil {
		rtk.AssignFlag(scope, "config", &i.Flags.Config)
		rtk.AssignFlag(scope, "help", &i.Flags.Help)
		rtk.AssignFlag(scope, "watch", &i.Flags.Watch)
	}
	rtk.AssignStringArg(r.ParsedArgs, 0, &i.Arguments.File)
	_ = r
	return nil
}

// HelpFlags carries the "help" command's own flags.
type HelpFlags struct {
	Help bool
}

// HelpArguments carries the "help" command's positional arguments.
type HelpArguments struct {
	Command []string
}

// HelpInputs is the typed input for the "help" command.
// It composes the root program-level flags (RootFlags) plus the
// command's own flags and positional arguments. Intermediate-ancestor
// flag scopes are exposed under per-segment fields.
type HelpInputs struct {
	RootFlags RootFlags
	Flags     HelpFlags
	Arguments HelpArguments
}

// RotiniCommandPath returns the hyphen-joined command path "help".
func (i *HelpInputs) RotiniCommandPath() string { return "help" }

// PopulateFromArgv reads parsed flag and argument values into i.
func (i *HelpInputs) PopulateFromArgv(r *rtk.Result) error {
	if scope := r.FlagsByScope[""]; scope != nil {
		rtk.AssignFlag(scope, "help", &i.RootFlags.Help)
		rtk.AssignFlag(scope, "version", &i.RootFlags.Version)
	}
	if scope := r.FlagsByScope["help"]; scope != nil {
		rtk.AssignFlag(scope, "help", &i.Flags.Help)
	}
	rtk.AssignVariadicStringArg(r.ParsedArgs, 0, &i.Arguments.Command)
	_ = r
	return nil
}

// InitializeFlags carries the "initialize" command's own flags.
type InitializeFlags struct {
	Format string
	Force  bool
	Help   bool
}

// InitializeArguments carries the "initialize" command's positional arguments.
type InitializeArguments struct {
	Name string
}

// InitializeInputs is the typed input for the "initialize" command.
// It composes the root program-level flags (RootFlags) plus the
// command's own flags and positional arguments. Intermediate-ancestor
// flag scopes are exposed under per-segment fields.
type InitializeInputs struct {
	RootFlags RootFlags
	Flags     InitializeFlags
	Arguments InitializeArguments
}

// RotiniCommandPath returns the hyphen-joined command path "initialize".
func (i *InitializeInputs) RotiniCommandPath() string { return "initialize" }

// PopulateFromArgv reads parsed flag and argument values into i.
func (i *InitializeInputs) PopulateFromArgv(r *rtk.Result) error {
	if scope := r.FlagsByScope[""]; scope != nil {
		rtk.AssignFlag(scope, "help", &i.RootFlags.Help)
		rtk.AssignFlag(scope, "version", &i.RootFlags.Version)
	}
	if scope := r.FlagsByScope["initialize"]; scope != nil {
		rtk.AssignFlag(scope, "format", &i.Flags.Format)
		rtk.AssignFlag(scope, "force", &i.Flags.Force)
		rtk.AssignFlag(scope, "help", &i.Flags.Help)
	}
	rtk.AssignStringArg(r.ParsedArgs, 0, &i.Arguments.Name)
	_ = r
	return nil
}

// ValidateFlags carries the "validate" command's own flags.
type ValidateFlags struct {
	Help bool
}

// ValidateArguments carries the "validate" command's positional arguments.
type ValidateArguments struct {
	File string
}

// ValidateInputs is the typed input for the "validate" command.
// It composes the root program-level flags (RootFlags) plus the
// command's own flags and positional arguments. Intermediate-ancestor
// flag scopes are exposed under per-segment fields.
type ValidateInputs struct {
	RootFlags RootFlags
	Flags     ValidateFlags
	Arguments ValidateArguments
}

// RotiniCommandPath returns the hyphen-joined command path "validate".
func (i *ValidateInputs) RotiniCommandPath() string { return "validate" }

// PopulateFromArgv reads parsed flag and argument values into i.
func (i *ValidateInputs) PopulateFromArgv(r *rtk.Result) error {
	if scope := r.FlagsByScope[""]; scope != nil {
		rtk.AssignFlag(scope, "help", &i.RootFlags.Help)
		rtk.AssignFlag(scope, "version", &i.RootFlags.Version)
	}
	if scope := r.FlagsByScope["validate"]; scope != nil {
		rtk.AssignFlag(scope, "help", &i.Flags.Help)
	}
	rtk.AssignStringArg(r.ParsedArgs, 0, &i.Arguments.File)
	_ = r
	return nil
}

// VersionFlags carries the "version" command's own flags.
type VersionFlags struct {
	Help bool
}

// VersionInputs is the typed input for the "version" command.
// It composes the root program-level flags (RootFlags) plus the
// command's own flags and positional arguments. Intermediate-ancestor
// flag scopes are exposed under per-segment fields.
type VersionInputs struct {
	RootFlags RootFlags
	Flags     VersionFlags
}

// RotiniCommandPath returns the hyphen-joined command path "version".
func (i *VersionInputs) RotiniCommandPath() string { return "version" }

// PopulateFromArgv reads parsed flag and argument values into i.
func (i *VersionInputs) PopulateFromArgv(r *rtk.Result) error {
	if scope := r.FlagsByScope[""]; scope != nil {
		rtk.AssignFlag(scope, "help", &i.RootFlags.Help)
		rtk.AssignFlag(scope, "version", &i.RootFlags.Version)
	}
	if scope := r.FlagsByScope["version"]; scope != nil {
		rtk.AssignFlag(scope, "help", &i.Flags.Help)
	}
	_ = r
	return nil
}
