// Code generated by rotini; DO NOT EDIT.
package rotini

import (
	"errors"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/go-rotini/rotini/rtk"
)

// =============================================================================
// Spec
// =============================================================================

// Spec is the resolved program specification. The rotini framework
// consults it to drive argv tokenization, env/config fallback, and
// validation before each handler runs. Regenerate by re-running
// `go tool rotini generate` against the project's .rotini.spec.yaml.
var Spec = rtk.ProgramSpec{
	Name: "rotini",
	Flags: []rtk.FlagSpec{
		{Name: "help", Identifiers: []string{"-h", "--help"}, Type: "bool"},
		{Name: "version", Identifiers: []string{"-v", "--version"}, Type: "bool"},
	},
	Commands: []rtk.CommandSpec{
		{
			Path:    "initialize",
			Name:    "initialize",
			Aliases: []string{"init"},
			Flags: []rtk.FlagSpec{
				{Name: "format", Identifiers: []string{"--format"}, Type: "string", Default: "yaml", Enum: []string{"yaml", "json", "jsonc"}},
				{Name: "force", Identifiers: []string{"--force"}, Type: "bool"},
				{Name: "help", Identifiers: []string{"-h", "--help"}, Type: "bool"},
			},
			Arguments: []rtk.ArgumentSpec{
				{Name: "name", Type: "string"},
			},
		},
		{
			Path:    "generate",
			Name:    "generate",
			Aliases: []string{"gen"},
			Flags: []rtk.FlagSpec{
				{Name: "config", Identifiers: []string{"-c", "--config"}, Type: "string"},
				{Name: "help", Identifiers: []string{"-h", "--help"}, Type: "bool"},
				{Name: "watch", Identifiers: []string{"--watch", "-w"}, Type: "bool"},
			},
			Arguments: []rtk.ArgumentSpec{
				{Name: "file", Type: "string", Default: ".rotini.spec.yaml"},
			},
		},
		{
			Path:    "validate",
			Name:    "validate",
			Aliases: []string{"val"},
			Flags: []rtk.FlagSpec{
				{Name: "help", Identifiers: []string{"-h", "--help"}, Type: "bool"},
			},
			Arguments: []rtk.ArgumentSpec{
				{Name: "file", Type: "string", Default: ".rotini.spec.yaml"},
			},
		},
		{
			Path: "help",
			Name: "help",
			Flags: []rtk.FlagSpec{
				{Name: "help", Identifiers: []string{"-h", "--help"}, Type: "bool"},
			},
			Arguments: []rtk.ArgumentSpec{
				{Name: "command", Type: "[]string", Variadic: true},
			},
		},
		{
			Path: "version",
			Name: "version",
			Flags: []rtk.FlagSpec{
				{Name: "help", Identifiers: []string{"-h", "--help"}, Type: "bool"},
			},
		},
		{
			Path: "completion",
			Name: "completion",
			Flags: []rtk.FlagSpec{
				{Name: "help", Identifiers: []string{"-h", "--help"}, Type: "bool"},
			},
			Arguments: []rtk.ArgumentSpec{
				{Name: "shell", Type: "string", Enum: []string{"zsh", "bash", "fish", "powershell", "nushell", "elvish"}},
			},
		},
	},
}

// =============================================================================
// Inputs — per-command Flags / Arguments / Inputs types + PopulateFromArgv
// =============================================================================

// RootFlags carries the root command's program-level flags. Each
// sub-command's Inputs type composes RootFlags so handlers see the
// inherited program scope alongside their own.
type RootFlags struct {
	Help    bool
	Version bool
}

// RootInputs is the typed input for invocations of the root command
// (no sub-command supplied).
type RootInputs struct {
	Flags RootFlags
}

// RotiniCommandPath returns the empty string for the root command.
func (i *RootInputs) RotiniCommandPath() string { return "" }

// PopulateFromArgv reads parsed root-scope flag values into i.
func (i *RootInputs) PopulateFromArgv(r *rtk.Result) error {
	if scope := r.FlagsByScope[""]; scope != nil {
		rtk.AssignFlag(scope, "help", &i.Flags.Help)
		rtk.AssignFlag(scope, "version", &i.Flags.Version)
	}
	_ = r
	return nil
}

// CompletionFlags carries the "completion" command's own flags.
type CompletionFlags struct {
	Help bool
}

// CompletionArguments carries the "completion" command's positional arguments.
type CompletionArguments struct {
	Shell string
}

// CompletionInputs is the typed input for the "completion" command.
// It composes the root program-level flags (RootFlags) plus the
// command's own flags and positional arguments. Intermediate-ancestor
// flag scopes are exposed under per-segment fields.
type CompletionInputs struct {
	RootFlags RootFlags
	Flags     CompletionFlags
	Arguments CompletionArguments
}

// RotiniCommandPath returns the hyphen-joined command path "completion".
func (i *CompletionInputs) RotiniCommandPath() string { return "completion" }

// PopulateFromArgv reads parsed flag and argument values into i.
func (i *CompletionInputs) PopulateFromArgv(r *rtk.Result) error {
	if scope := r.FlagsByScope[""]; scope != nil {
		rtk.AssignFlag(scope, "help", &i.RootFlags.Help)
		rtk.AssignFlag(scope, "version", &i.RootFlags.Version)
	}
	if scope := r.FlagsByScope["completion"]; scope != nil {
		rtk.AssignFlag(scope, "help", &i.Flags.Help)
	}
	rtk.AssignStringArg(r.ParsedArgs, 0, &i.Arguments.Shell)
	_ = r
	return nil
}

// GenerateFlags carries the "generate" command's own flags.
type GenerateFlags struct {
	Config string
	Help   bool
	Watch  bool
}

// GenerateArguments carries the "generate" command's positional arguments.
type GenerateArguments struct {
	File string
}

// GenerateInputs is the typed input for the "generate" command.
// It composes the root program-level flags (RootFlags) plus the
// command's own flags and positional arguments. Intermediate-ancestor
// flag scopes are exposed under per-segment fields.
type GenerateInputs struct {
	RootFlags RootFlags
	Flags     GenerateFlags
	Arguments GenerateArguments
}

// RotiniCommandPath returns the hyphen-joined command path "generate".
func (i *GenerateInputs) RotiniCommandPath() string { return "generate" }

// PopulateFromArgv reads parsed flag and argument values into i.
func (i *GenerateInputs) PopulateFromArgv(r *rtk.Result) error {
	if scope := r.FlagsByScope[""]; scope != nil {
		rtk.AssignFlag(scope, "help", &i.RootFlags.Help)
		rtk.AssignFlag(scope, "version", &i.RootFlags.Version)
	}
	if scope := r.FlagsByScope["generate"]; scope != nil {
		rtk.AssignFlag(scope, "config", &i.Flags.Config)
		rtk.AssignFlag(scope, "help", &i.Flags.Help)
		rtk.AssignFlag(scope, "watch", &i.Flags.Watch)
	}
	rtk.AssignStringArg(r.ParsedArgs, 0, &i.Arguments.File)
	_ = r
	return nil
}

// HelpFlags carries the "help" command's own flags.
type HelpFlags struct {
	Help bool
}

// HelpArguments carries the "help" command's positional arguments.
type HelpArguments struct {
	Command []string
}

// HelpInputs is the typed input for the "help" command.
// It composes the root program-level flags (RootFlags) plus the
// command's own flags and positional arguments. Intermediate-ancestor
// flag scopes are exposed under per-segment fields.
type HelpInputs struct {
	RootFlags RootFlags
	Flags     HelpFlags
	Arguments HelpArguments
}

// RotiniCommandPath returns the hyphen-joined command path "help".
func (i *HelpInputs) RotiniCommandPath() string { return "help" }

// PopulateFromArgv reads parsed flag and argument values into i.
func (i *HelpInputs) PopulateFromArgv(r *rtk.Result) error {
	if scope := r.FlagsByScope[""]; scope != nil {
		rtk.AssignFlag(scope, "help", &i.RootFlags.Help)
		rtk.AssignFlag(scope, "version", &i.RootFlags.Version)
	}
	if scope := r.FlagsByScope["help"]; scope != nil {
		rtk.AssignFlag(scope, "help", &i.Flags.Help)
	}
	rtk.AssignVariadicStringArg(r.ParsedArgs, 0, &i.Arguments.Command)
	_ = r
	return nil
}

// InitializeFlags carries the "initialize" command's own flags.
type InitializeFlags struct {
	Format string
	Force  bool
	Help   bool
}

// InitializeArguments carries the "initialize" command's positional arguments.
type InitializeArguments struct {
	Name string
}

// InitializeInputs is the typed input for the "initialize" command.
// It composes the root program-level flags (RootFlags) plus the
// command's own flags and positional arguments. Intermediate-ancestor
// flag scopes are exposed under per-segment fields.
type InitializeInputs struct {
	RootFlags RootFlags
	Flags     InitializeFlags
	Arguments InitializeArguments
}

// RotiniCommandPath returns the hyphen-joined command path "initialize".
func (i *InitializeInputs) RotiniCommandPath() string { return "initialize" }

// PopulateFromArgv reads parsed flag and argument values into i.
func (i *InitializeInputs) PopulateFromArgv(r *rtk.Result) error {
	if scope := r.FlagsByScope[""]; scope != nil {
		rtk.AssignFlag(scope, "help", &i.RootFlags.Help)
		rtk.AssignFlag(scope, "version", &i.RootFlags.Version)
	}
	if scope := r.FlagsByScope["initialize"]; scope != nil {
		rtk.AssignFlag(scope, "format", &i.Flags.Format)
		rtk.AssignFlag(scope, "force", &i.Flags.Force)
		rtk.AssignFlag(scope, "help", &i.Flags.Help)
	}
	rtk.AssignStringArg(r.ParsedArgs, 0, &i.Arguments.Name)
	_ = r
	return nil
}

// ValidateFlags carries the "validate" command's own flags.
type ValidateFlags struct {
	Help bool
}

// ValidateArguments carries the "validate" command's positional arguments.
type ValidateArguments struct {
	File string
}

// ValidateInputs is the typed input for the "validate" command.
// It composes the root program-level flags (RootFlags) plus the
// command's own flags and positional arguments. Intermediate-ancestor
// flag scopes are exposed under per-segment fields.
type ValidateInputs struct {
	RootFlags RootFlags
	Flags     ValidateFlags
	Arguments ValidateArguments
}

// RotiniCommandPath returns the hyphen-joined command path "validate".
func (i *ValidateInputs) RotiniCommandPath() string { return "validate" }

// PopulateFromArgv reads parsed flag and argument values into i.
func (i *ValidateInputs) PopulateFromArgv(r *rtk.Result) error {
	if scope := r.FlagsByScope[""]; scope != nil {
		rtk.AssignFlag(scope, "help", &i.RootFlags.Help)
		rtk.AssignFlag(scope, "version", &i.RootFlags.Version)
	}
	if scope := r.FlagsByScope["validate"]; scope != nil {
		rtk.AssignFlag(scope, "help", &i.Flags.Help)
	}
	rtk.AssignStringArg(r.ParsedArgs, 0, &i.Arguments.File)
	_ = r
	return nil
}

// VersionFlags carries the "version" command's own flags.
type VersionFlags struct {
	Help bool
}

// VersionInputs is the typed input for the "version" command.
// It composes the root program-level flags (RootFlags) plus the
// command's own flags and positional arguments. Intermediate-ancestor
// flag scopes are exposed under per-segment fields.
type VersionInputs struct {
	RootFlags RootFlags
	Flags     VersionFlags
}

// RotiniCommandPath returns the hyphen-joined command path "version".
func (i *VersionInputs) RotiniCommandPath() string { return "version" }

// PopulateFromArgv reads parsed flag and argument values into i.
func (i *VersionInputs) PopulateFromArgv(r *rtk.Result) error {
	if scope := r.FlagsByScope[""]; scope != nil {
		rtk.AssignFlag(scope, "help", &i.RootFlags.Help)
		rtk.AssignFlag(scope, "version", &i.RootFlags.Version)
	}
	if scope := r.FlagsByScope["version"]; scope != nil {
		rtk.AssignFlag(scope, "help", &i.Flags.Help)
	}
	_ = r
	return nil
}

// =============================================================================
// Handler interfaces + Ctx aliases + aggregate Handlers interface
// =============================================================================

// RootCtx is the [rtk.Ctx] alias for root-command handlers.
type RootCtx = rtk.Ctx

// RootHandler is the interface a root-command handler implementation
// satisfies. The framework calls Run after [RootInputs] has been
// populated from argv / env / config.
type RootHandler interface {
	Run(ctx RootCtx, inputs *RootInputs) error
}

// CompletionCtx is the [rtk.Ctx] alias for "completion" handlers.
type CompletionCtx = rtk.Ctx

// CompletionHandler is the interface a "completion" handler
// implementation satisfies.
type CompletionHandler interface {
	Run(ctx CompletionCtx, inputs *CompletionInputs) error
}

// GenerateCtx is the [rtk.Ctx] alias for "generate" handlers.
type GenerateCtx = rtk.Ctx

// GenerateHandler is the interface a "generate" handler
// implementation satisfies.
type GenerateHandler interface {
	Run(ctx GenerateCtx, inputs *GenerateInputs) error
}

// HelpCtx is the [rtk.Ctx] alias for "help" handlers.
type HelpCtx = rtk.Ctx

// HelpHandler is the interface a "help" handler
// implementation satisfies.
type HelpHandler interface {
	Run(ctx HelpCtx, inputs *HelpInputs) error
}

// InitializeCtx is the [rtk.Ctx] alias for "initialize" handlers.
type InitializeCtx = rtk.Ctx

// InitializeHandler is the interface a "initialize" handler
// implementation satisfies.
type InitializeHandler interface {
	Run(ctx InitializeCtx, inputs *InitializeInputs) error
}

// ValidateCtx is the [rtk.Ctx] alias for "validate" handlers.
type ValidateCtx = rtk.Ctx

// ValidateHandler is the interface a "validate" handler
// implementation satisfies.
type ValidateHandler interface {
	Run(ctx ValidateCtx, inputs *ValidateInputs) error
}

// VersionCtx is the [rtk.Ctx] alias for "version" handlers.
type VersionCtx = rtk.Ctx

// VersionHandler is the interface a "version" handler
// implementation satisfies.
type VersionHandler interface {
	Run(ctx VersionCtx, inputs *VersionInputs) error
}

// Handlers is the aggregate interface the user's handlers package
// satisfies. Each accessor returns the per-command handler the
// framework dispatches to.
type Handlers interface {
	Root() RootHandler
	Completion() CompletionHandler
	Generate() GenerateHandler
	Help() HelpHandler
	Initialize() InitializeHandler
	Validate() ValidateHandler
	Version() VersionHandler
}

// =============================================================================
// Lifecycle — SafeCall, Execution, RunExecution
// =============================================================================

// SafeCall wraps fn in a deferred recover() so a handler panic does
// not take down the entire process. Returns fn's error verbatim on
// normal return; converts panics into wrapped errors. *rtk.EarlyExit
// panics are preserved through the error chain so main()'s ExitCode()
// can pick up the requested exit code.
func SafeCall(fn func() error) (err error) {
	defer func() {
		if r := recover(); r != nil {
			if ee, ok := r.(*rtk.EarlyExit); ok {
				err = ee
				return
			}
			err = fmt.Errorf("rotini: handler panicked: %v", r)
		}
	}()
	return fn()
}

// Execution is the unit of dispatch a [Program] runs. It carries the
// matched command path and the closure that, when called, parses
// inputs and invokes the user's handler.
type Execution struct {
	Path string
	Run  func() error
}

// RunExecution invokes ex.Run wrapped in [SafeCall]. Returns
// [ErrEmptyExecution] when ex.Run is nil — a codegen bug rather than
// a user-input error.
func RunExecution(ex Execution) error {
	if ex.Run == nil {
		return ErrEmptyExecution
	}
	return SafeCall(ex.Run)
}

// ErrEmptyExecution indicates an Execution with no Run closure was
// dispatched. Always a generated-code bug.
var ErrEmptyExecution = errors.New("rotini: execution has nil Run closure")

// ErrParserUnbound is returned when an Execution closure runs but no
// Parser service is bound under the "parser" registry key. Always a
// generated-code bug.
var ErrParserUnbound = errors.New("rotini: parser service not bound")

// =============================================================================
// Executors — per-command Execution builders + dispatch map
// =============================================================================

// executors is the per-command-path dispatch map. [Program.Execute]
// looks up the matched command path and invokes the resulting
// [Execution] under [SafeCall].
var executors = map[string]func(*Program) Execution{
	"":           buildRootExecution,
	"completion": buildCompletionExecution,
	"generate":   buildGenerateExecution,
	"help":       buildHelpExecution,
	"initialize": buildInitializeExecution,
	"validate":   buildValidateExecution,
	"version":    buildVersionExecution,
}

// buildRootExecution builds the [Execution] for the root command.
func buildRootExecution(p *Program) Execution {
	return Execution{
		Path: "",
		Run: func() error {
			parser := rtk.Get[rtk.Parser](p.registry, "parser")
			if parser == nil {
				return ErrParserUnbound
			}
			var inputs RootInputs
			if err := parser.Parse(&inputs); err != nil {
				return err
			}
			return p.handlers.Root().Run(rtk.Ctx{Registry: p.registry}, &inputs)
		},
	}
}

// buildCompletionExecution builds the [Execution] for the
// "completion" command.
func buildCompletionExecution(p *Program) Execution {
	return Execution{
		Path: "completion",
		Run: func() error {
			parser := rtk.Get[rtk.Parser](p.registry, "parser")
			if parser == nil {
				return ErrParserUnbound
			}
			var inputs CompletionInputs
			if err := parser.Parse(&inputs); err != nil {
				return err
			}
			return p.handlers.Completion().Run(rtk.Ctx{Registry: p.registry}, &inputs)
		},
	}
}

// buildGenerateExecution builds the [Execution] for the
// "generate" command.
func buildGenerateExecution(p *Program) Execution {
	return Execution{
		Path: "generate",
		Run: func() error {
			parser := rtk.Get[rtk.Parser](p.registry, "parser")
			if parser == nil {
				return ErrParserUnbound
			}
			var inputs GenerateInputs
			if err := parser.Parse(&inputs); err != nil {
				return err
			}
			return p.handlers.Generate().Run(rtk.Ctx{Registry: p.registry}, &inputs)
		},
	}
}

// buildHelpExecution builds the [Execution] for the
// "help" command.
func buildHelpExecution(p *Program) Execution {
	return Execution{
		Path: "help",
		Run: func() error {
			parser := rtk.Get[rtk.Parser](p.registry, "parser")
			if parser == nil {
				return ErrParserUnbound
			}
			var inputs HelpInputs
			if err := parser.Parse(&inputs); err != nil {
				return err
			}
			return p.handlers.Help().Run(rtk.Ctx{Registry: p.registry}, &inputs)
		},
	}
}

// buildInitializeExecution builds the [Execution] for the
// "initialize" command.
func buildInitializeExecution(p *Program) Execution {
	return Execution{
		Path: "initialize",
		Run: func() error {
			parser := rtk.Get[rtk.Parser](p.registry, "parser")
			if parser == nil {
				return ErrParserUnbound
			}
			var inputs InitializeInputs
			if err := parser.Parse(&inputs); err != nil {
				return err
			}
			return p.handlers.Initialize().Run(rtk.Ctx{Registry: p.registry}, &inputs)
		},
	}
}

// buildValidateExecution builds the [Execution] for the
// "validate" command.
func buildValidateExecution(p *Program) Execution {
	return Execution{
		Path: "validate",
		Run: func() error {
			parser := rtk.Get[rtk.Parser](p.registry, "parser")
			if parser == nil {
				return ErrParserUnbound
			}
			var inputs ValidateInputs
			if err := parser.Parse(&inputs); err != nil {
				return err
			}
			return p.handlers.Validate().Run(rtk.Ctx{Registry: p.registry}, &inputs)
		},
	}
}

// buildVersionExecution builds the [Execution] for the
// "version" command.
func buildVersionExecution(p *Program) Execution {
	return Execution{
		Path: "version",
		Run: func() error {
			parser := rtk.Get[rtk.Parser](p.registry, "parser")
			if parser == nil {
				return ErrParserUnbound
			}
			var inputs VersionInputs
			if err := parser.Parse(&inputs); err != nil {
				return err
			}
			return p.handlers.Version().Run(rtk.Ctx{Registry: p.registry}, &inputs)
		},
	}
}

// =============================================================================
// Program — entrypoint type + NewProgram + Execute auto-binding rtk services
// =============================================================================

// Program is the assembled CLI. Construct via [NewProgram], then call
// [Program.Execute] from main().
type Program struct {
	registry *rtk.Registry
	handlers Handlers
}

// NewProgram returns a Program wired with the supplied Handlers and
// the rtk-default services (IO, OS, Signals, Ticker) bound under the
// well-known keys "io", "os", "signals", "ticker".
func NewProgram(h Handlers) *Program {
	reg := rtk.NewRegistry()
	reg.Bind("io", rtk.NewIO())
	reg.Bind("os", rtk.NewOS())
	reg.Bind("signals", rtk.NewSignals())
	reg.Bind("ticker", rtk.NewTicker())
	return &Program{registry: reg, handlers: h}
}

// Registry returns the program's service registry. Callers can bind
// overrides (e.g., for tests) before calling Execute.
func (p *Program) Registry() *rtk.Registry { return p.registry }

// Execute parses os.Args[1:] and dispatches to the matched command's
// handler. Returns the handler's error verbatim — rtk error types
// such as *EarlyExit propagate through so main()'s ExitCode mapping
// can act on them.
func (p *Program) Execute() error {
	return p.ExecuteArgs(os.Args[1:])
}

// ExecuteArgs is the testable form of [Program.Execute]: argv is
// supplied explicitly so tests don't have to mutate os.Args.
func (p *Program) ExecuteArgs(argv []string) error {
	ros := rtk.Get[rtk.OS](p.registry, "os")
	if ros == nil {
		ros = rtk.NewOS()
	}
	parser := rtk.NewParser(Spec, rtk.Inputs{
		Argv:  argv,
		Stdin: os.Stdin,
		Env:   ros,
	})
	p.registry.Bind("parser", parser)

	tok, err := rtk.Tokenize(argv, Spec)
	if err != nil {
		return err
	}
	path := strings.Join(tok.CommandPath, "-")

	build, ok := executors[path]
	if !ok {
		return errors.New("rotini: no executor for command path " + path)
	}
	return RunExecution(build(p))
}

// =============================================================================
// Completion — per-program accessor wrapping rtk.GenerateCompletion
// =============================================================================

// Completion returns a shell-completion script for the program's
// spec. shell is one of [rtk.SupportedShells]. Returns
// [rtk.ErrUnknownShell] for an unrecognized shell name.
func Completion(shell rtk.Shell) (string, error) {
	return rtk.GenerateCompletion(shell, Spec)
}

// =============================================================================
// Render — RenderError + ExitCode
// =============================================================================

// RenderError writes a human-readable representation of err to w.
// Recognized rtk error types get a brief category prefix so users
// can tell at a glance what kind of failure occurred.
func RenderError(w io.Writer, err error) {
	if w == nil || err == nil {
		return
	}
	prefix := "rotini"
	if prefix == "" {
		prefix = "rotini"
	}

	var (
		unkCmd *rtk.UnknownCommandError
		unkFlg *rtk.UnknownFlagError
		unkArg *rtk.UnknownArgumentError
		missR  *rtk.MissingRequiredError
		coerce *rtk.CoercionError
		valid  *rtk.ValidationError
	)
	switch {
	case errors.As(err, &unkCmd):
		fmt.Fprintf(w, "%s: unknown command: %s\n", prefix, unkCmd.Error())
	case errors.As(err, &unkFlg):
		fmt.Fprintf(w, "%s: unknown flag: %s\n", prefix, unkFlg.Error())
	case errors.As(err, &unkArg):
		fmt.Fprintf(w, "%s: %s\n", prefix, unkArg.Error())
	case errors.As(err, &missR):
		fmt.Fprintf(w, "%s: %s\n", prefix, missR.Error())
	case errors.As(err, &coerce):
		fmt.Fprintf(w, "%s: %s\n", prefix, coerce.Error())
	case errors.As(err, &valid):
		fmt.Fprintf(w, "%s: %s\n", prefix, valid.Error())
	default:
		fmt.Fprintf(w, "%s: %s\n", prefix, err.Error())
	}
}

// ExitCode maps an error to a process exit code suitable for os.Exit.
// nil → 0. *rtk.EarlyExit carries an explicit code through. Anything
// else returns 1.
func ExitCode(err error) int {
	if err == nil {
		return 0
	}
	var ee *rtk.EarlyExit
	if errors.As(err, &ee) {
		return ee.Code
	}
	return 1
}
