// Code generated by rotini; DO NOT EDIT.
package rtg

import (
	"github.com/go-rotini/rotini"
)

type ProgramHandlers interface {
	Rotini() rotini.CommandHandlers
	RotiniCompletion() rotini.CommandHandlers
	RotiniGenerate() rotini.CommandHandlers
	RotiniHelp() rotini.CommandHandlers
	RotiniInitialize() rotini.CommandHandlers
	RotiniValidate() rotini.CommandHandlers
	RotiniVersion() rotini.CommandHandlers
}

type RotiniFlags struct {
	Help    bool
	Version bool
}

type RotiniArguments struct{}

type RotiniCommandInputs struct {
	Flags     RotiniFlags
	Arguments RotiniArguments
}

type RotiniInputs struct {
	Rotini RotiniCommandInputs
}

type RotiniCompletionFlags struct {
	Help bool
}

type RotiniCompletionArguments struct {
	Shell string
}

type RotiniCompletionCommandInputs struct {
	Flags     RotiniCompletionFlags
	Arguments RotiniCompletionArguments
}

type RotiniCompletionInputs struct {
	Rotini           RotiniCommandInputs
	RotiniCompletion RotiniCompletionCommandInputs
}

type RotiniGenerateFlags struct {
	Config string
	Help   bool
	Watch  bool
}

type RotiniGenerateArguments struct {
	File string
}

type RotiniGenerateCommandInputs struct {
	Flags     RotiniGenerateFlags
	Arguments RotiniGenerateArguments
}

type RotiniGenerateInputs struct {
	Rotini         RotiniCommandInputs
	RotiniGenerate RotiniGenerateCommandInputs
}

type RotiniHelpFlags struct {
	Help bool
}

type RotiniHelpArguments struct {
	Command []string
}

type RotiniHelpCommandInputs struct {
	Flags     RotiniHelpFlags
	Arguments RotiniHelpArguments
}

type RotiniHelpInputs struct {
	Rotini     RotiniCommandInputs
	RotiniHelp RotiniHelpCommandInputs
}

type RotiniInitializeFlags struct {
	Format string
	Force  bool
	Help   bool
}

type RotiniInitializeArguments struct {
	Name string
}

type RotiniInitializeCommandInputs struct {
	Flags     RotiniInitializeFlags
	Arguments RotiniInitializeArguments
}

type RotiniInitializeInputs struct {
	Rotini           RotiniCommandInputs
	RotiniInitialize RotiniInitializeCommandInputs
}

type RotiniValidateFlags struct {
	Help bool
}

type RotiniValidateArguments struct {
	File string
}

type RotiniValidateCommandInputs struct {
	Flags     RotiniValidateFlags
	Arguments RotiniValidateArguments
}

type RotiniValidateInputs struct {
	Rotini         RotiniCommandInputs
	RotiniValidate RotiniValidateCommandInputs
}

type RotiniVersionFlags struct {
	Help bool
}

type RotiniVersionArguments struct{}

type RotiniVersionCommandInputs struct {
	Flags     RotiniVersionFlags
	Arguments RotiniVersionArguments
}

type RotiniVersionInputs struct {
	Rotini        RotiniCommandInputs
	RotiniVersion RotiniVersionCommandInputs
}
