// Code generated by rotini; DO NOT EDIT.
package rtg

import (
	_ "embed"
	"fmt"
	"github.com/go-rotini/rotini"
	"strings"
)

type ProgramHandlers interface {
	Rotini() rotini.CommandHandlers
	RotiniCompletion() rotini.CommandHandlers
	RotiniGenerate() rotini.CommandHandlers
	RotiniHelp() rotini.CommandHandlers
	RotiniInitialize() rotini.CommandHandlers
	RotiniValidate() rotini.CommandHandlers
	RotiniVersion() rotini.CommandHandlers
}

// Version is set at build time via -ldflags "-X <pkg>.Version=<value>".
var Version = "0.0.0"

var Definition = rotini.Definition{
	Name:    "rotini",
	Handler: "Rotini",
	Flags: []rotini.FlagDef{
		{Name: "version", Identifiers: []string{"-v", "--version"}, Type: "bool"},
		{Name: "help", Identifiers: []string{"-h", "--help"}, Type: "bool"},
	},
	Version: Version,
	Commands: []rotini.CommandDef{
		{Name: "initialize",
			Handler: "RotiniInitialize",
			Aliases: []string{"init"},
			Flags: []rotini.FlagDef{
				{Name: "format", Identifiers: []string{"--format"}, Type: "string", Default: "yaml", Enum: []string{"json", "yaml"}},
				{Name: "force", Identifiers: []string{"--force"}, Type: "bool"},
				{Name: "into", Identifiers: []string{"--into"}, Type: "string"},
				{Name: "help", Identifiers: []string{"-h", "--help"}, Type: "bool"},
			},
			Arguments: []rotini.ArgDef{
				{Name: "name", Type: "string"},
			},
		},
		{Name: "generate",
			Handler: "RotiniGenerate",
			Aliases: []string{"gen"},
			Flags: []rotini.FlagDef{
				{Name: "conf_file_path", Identifiers: []string{"-c", "--config"}, Type: "string"},
				{Name: "watch", Identifiers: []string{"--watch", "-w"}, Type: "bool"},
				{Name: "help", Identifiers: []string{"-h", "--help"}, Type: "bool"},
			},
			Arguments: []rotini.ArgDef{
				{Name: "spec_file_path", Type: "string", Default: ".rotini.spec.yaml"},
			},
		},
		{Name: "validate",
			Handler: "RotiniValidate",
			Aliases: []string{"val"},
			Flags: []rotini.FlagDef{
				{Name: "help", Identifiers: []string{"-h", "--help"}, Type: "bool"},
			},
			Arguments: []rotini.ArgDef{
				{Name: "file", Type: "string", Default: ".rotini.spec.yaml"},
			},
		},
		{Name: "completion",
			Handler: "RotiniCompletion",
			Flags: []rotini.FlagDef{
				{Name: "help", Identifiers: []string{"-h", "--help"}, Type: "bool"},
			},
			Arguments: []rotini.ArgDef{
				{Name: "shell", Type: "string", Enum: []string{"zsh", "bash", "fish", "powershell", "nushell", "elvish"}},
			},
		},
		{Name: "help",
			Handler: "RotiniHelp",
			Flags: []rotini.FlagDef{
				{Name: "help", Identifiers: []string{"-h", "--help"}, Type: "bool"},
			},
			Arguments: []rotini.ArgDef{
				{Name: "command", Type: "[]string", Variadic: true},
			},
		},
		{Name: "version",
			Handler: "RotiniVersion",
			Flags: []rotini.FlagDef{
				{Name: "help", Identifiers: []string{"-h", "--help"}, Type: "bool"},
			},
		},
	},
}

type RotiniFlags struct {
	Version bool `rotini:"version"`
	Help    bool `rotini:"help"`
}

type RotiniArguments struct{}

type RotiniCommandInputs struct {
	Flags     RotiniFlags
	Arguments RotiniArguments
}

type RotiniInputs struct {
	Rotini RotiniCommandInputs
}

type RotiniCompletionFlags struct {
	Help bool `rotini:"help"`
}

type RotiniCompletionArguments struct {
	Shell string `rotini:"shell"`
}

type RotiniCompletionCommandInputs struct {
	Flags     RotiniCompletionFlags
	Arguments RotiniCompletionArguments
}

type RotiniCompletionInputs struct {
	Rotini           RotiniCommandInputs
	RotiniCompletion RotiniCompletionCommandInputs
}

type RotiniGenerateFlags struct {
	ConfFilePath string `rotini:"conf_file_path"`
	Watch        bool   `rotini:"watch"`
	Help         bool   `rotini:"help"`
}

type RotiniGenerateArguments struct {
	SpecFilePath string `rotini:"spec_file_path"`
}

type RotiniGenerateCommandInputs struct {
	Flags     RotiniGenerateFlags
	Arguments RotiniGenerateArguments
}

type RotiniGenerateInputs struct {
	Rotini         RotiniCommandInputs
	RotiniGenerate RotiniGenerateCommandInputs
}

type RotiniHelpFlags struct {
	Help bool `rotini:"help"`
}

type RotiniHelpArguments struct {
	Command []string `rotini:"command"`
}

type RotiniHelpCommandInputs struct {
	Flags     RotiniHelpFlags
	Arguments RotiniHelpArguments
}

type RotiniHelpInputs struct {
	Rotini     RotiniCommandInputs
	RotiniHelp RotiniHelpCommandInputs
}

type RotiniInitializeFlags struct {
	Format string `rotini:"format"`
	Force  bool   `rotini:"force"`
	Into   string `rotini:"into"`
	Help   bool   `rotini:"help"`
}

type RotiniInitializeArguments struct {
	Name string `rotini:"name"`
}

type RotiniInitializeCommandInputs struct {
	Flags     RotiniInitializeFlags
	Arguments RotiniInitializeArguments
}

type RotiniInitializeInputs struct {
	Rotini           RotiniCommandInputs
	RotiniInitialize RotiniInitializeCommandInputs
}

type RotiniValidateFlags struct {
	Help bool `rotini:"help"`
}

type RotiniValidateArguments struct {
	File string `rotini:"file"`
}

type RotiniValidateCommandInputs struct {
	Flags     RotiniValidateFlags
	Arguments RotiniValidateArguments
}

type RotiniValidateInputs struct {
	Rotini         RotiniCommandInputs
	RotiniValidate RotiniValidateCommandInputs
}

type RotiniVersionFlags struct {
	Help bool `rotini:"help"`
}

type RotiniVersionArguments struct{}

type RotiniVersionCommandInputs struct {
	Flags     RotiniVersionFlags
	Arguments RotiniVersionArguments
}

type RotiniVersionInputs struct {
	Rotini        RotiniCommandInputs
	RotiniVersion RotiniVersionCommandInputs
}

// NewProgram builds the program from the generated Definition and the typed
// ProgramHandlers, delegating to rotini.NewProgram (which takes the handlers
// as an untyped value). Construct your program with this so the compiler verifies
// your handlers satisfy ProgramHandlers.
func NewProgram(handlers ProgramHandlers) *rotini.Program {
	return rotini.NewProgram(Definition, handlers)
}

//go:embed help/rotini.txt
var HelpRotini string

//go:embed help/rotini_initialize.txt
var HelpRotiniInitialize string

//go:embed help/rotini_generate.txt
var HelpRotiniGenerate string

//go:embed help/rotini_validate.txt
var HelpRotiniValidate string

//go:embed help/rotini_completion.txt
var HelpRotiniCompletion string

//go:embed help/rotini_help.txt
var HelpRotiniHelp string

//go:embed help/rotini_version.txt
var HelpRotiniVersion string

// Help returns the generated help text for the command identified by path
// (command names or aliases; no arguments for the root command). It returns an
// error when path does not match a known command.
func Help(path ...string) (string, error) {
	switch strings.Join(path, " ") {
	case "":
		return HelpRotini, nil
	case "initialize", "init":
		return HelpRotiniInitialize, nil
	case "generate", "gen":
		return HelpRotiniGenerate, nil
	case "validate", "val":
		return HelpRotiniValidate, nil
	case "completion":
		return HelpRotiniCompletion, nil
	case "help":
		return HelpRotiniHelp, nil
	case "version":
		return HelpRotiniVersion, nil
	default:
		return "", fmt.Errorf("no help for command %q", strings.Join(path, " "))
	}
}
