// Code generated by rotini; DO NOT EDIT.
package handlers

import (
	"github.com/go-rotini/rotini/internal/rotini/gen"
)

type handlers struct{}

var _ gen.Handlers = (*handlers)(nil)

var Program = gen.NewProgram(&handlers{})

func (*handlers) Rotini() gen.RotiniHandlers {
	return &rotiniHandlers{}
}

func (*handlers) RotiniCompletion() gen.RotiniCompletionHandlers {
	return &rotiniCompletionHandlers{}
}

func (*handlers) RotiniGenerate() gen.RotiniGenerateHandlers {
	return &rotiniGenerateHandlers{}
}

func (*handlers) RotiniHelp() gen.RotiniHelpHandlers {
	return &rotiniHelpHandlers{}
}

func (*handlers) RotiniInitialize() gen.RotiniInitializeHandlers {
	return &rotiniInitializeHandlers{}
}

func (*handlers) RotiniValidate() gen.RotiniValidateHandlers {
	return &rotiniValidateHandlers{}
}

func (*handlers) RotiniVersion() gen.RotiniVersionHandlers {
	return &rotiniVersionHandlers{}
}
