// Code generated by jsonschema; DO NOT EDIT.

package internal

// Schema for a Rotini CLI configuration file.
type Conf struct {
	// URL identifying the rotini configuration schema version. The version segment must match the installed rotini binary version.
	Schema   string          `json:"$schema"`
	Generate *GenerateConfig `json:"generate,omitempty"`
}

type GenerateCmdConfig struct {
	// Name of the framework-controlled gen file placed in the command handler package (e.g. 'handlers.gen.go'). Must end in .go.
	GenFile string `json:"gen_file,omitempty"`
	// Import path (relative to module root) for the command handler package. Package name is derived from the last path segment.
	Package string       `json:"package,omitempty"`
	Prune   *PruneConfig `json:"prune,omitempty"`
}

type GenerateConfig struct {
	Cmd       *GenerateCmdConfig       `json:"cmd,omitempty"`
	Framework *GenerateFrameworkConfig `json:"framework,omitempty"`
	Help      *GenerateHelpConfig      `json:"help,omitempty"`
}

type GenerateFrameworkConfig struct {
	// Additional Go import paths included in the generated framework file. Use when input or output types reference third-party packages. Each entry is a package path (e.g., 'net/url') or an aliased import (e.g., 'myalias net/url').
	AdditionalImports []string `json:"additional_imports,omitempty"`
	// Name of the framework gen file placed in the framework package (e.g. 'rotini.gen.go'). Must end in .go.
	GenFile string `json:"gen_file,omitempty"`
	// Import path (relative to module root) for the framework package. Package name is derived from the last path segment.
	Package string `json:"package,omitempty"`
}

// Controls generation of embedded, per-command help text.
type GenerateHelpConfig struct {
	// Subdirectory under the framework package where the per-command help .txt files (and the editable help.txt.tmpl) live and are embedded.
	Dir string `json:"dir,omitempty"`
	// When true, rotini produces a per-command help .txt for every command and embeds them in the framework package as 'Help<Prefix>' string vars plus a 'Help(path ...string) (string, error)' resolver. Each .txt is rotini-managed: when a command sets a verbatim 'help' string in the spec it is written exactly; otherwise the page is rendered from the command's structured help fields (summary/description/usage/...) via the help template.
	Enabled bool `json:"enabled,omitempty"`
}

// Controls pruning of stub files in the command handler package.
type PruneConfig struct {
	// When true, rotini removes stub files in the command handler package that no longer correspond to a command in the spec.
	Enabled bool `json:"enabled,omitempty"`
	// File names (not paths) that should never be removed by pruning, even when they do not correspond to a command in the spec.
	Keep []string `json:"keep,omitempty"`
}
