package internal_test

import (
	"go/format"
	"go/parser"
	"go/token"
	"strings"
	"testing"

	"github.com/go-rotini/rotini/internal"
	"github.com/go-rotini/rotini/rtk"
)

// =============================================================================
// Fixture spec used by most rendering tests
// =============================================================================

// fixtureSpec returns a small but representative spec covering:
//   - root flag (string with default)
//   - root flag (bool)
//   - one top-level command with a flag + required positional
//   - one nested command path (foo → foo-bar) to exercise the
//     ancestor-composition logic
func fixtureSpec() rtk.ProgramSpec {
	return rtk.ProgramSpec{
		Name: "todo",
		Flags: []rtk.FlagSpec{
			{Name: "output", Identifiers: []string{"-o", "--output"}, Type: "string", Default: "table"},
			{Name: "verbose", Identifiers: []string{"-v", "--verbose"}, Type: "bool"},
		},
		Commands: []rtk.CommandSpec{
			{
				Path: "add", Name: "add",
				Flags: []rtk.FlagSpec{
					{Name: "priority", Identifiers: []string{"-p"}, Type: "int"},
				},
				Arguments: []rtk.ArgumentSpec{
					{Name: "title", Type: "string", Required: true},
				},
			},
			{
				Path: "foo", Name: "foo",
				Flags: []rtk.FlagSpec{
					{Name: "fopt", Identifiers: []string{"--fopt"}, Type: "string"},
				},
				Commands: []rtk.CommandSpec{
					{
						Path: "foo-bar", Name: "bar",
						Flags: []rtk.FlagSpec{
							{Name: "bopt", Identifiers: []string{"--bopt"}, Type: "int"},
						},
					},
				},
			},
		},
	}
}

// =============================================================================
// Driver: render + gofmt + go-parse
// =============================================================================

// renderOK renders the named template and asserts the output is valid
// Go (passes go/parser). It returns the rendered bytes so callers can
// do additional structural assertions.
func renderOK(t *testing.T, name string, in internal.RenderInput) []byte {
	t.Helper()
	out, err := internal.Render(name, in)
	if err != nil {
		t.Fatalf("Render(%s): %v\n--- output so far ---\n%s", name, err, out)
	}
	reformatted, err := format.Source(out)
	if err != nil {
		t.Fatalf("re-format %s: %v", name, err)
	}
	if string(reformatted) != string(out) {
		t.Errorf("%s output not gofmt-idempotent", name)
	}
	if _, err := parser.ParseFile(token.NewFileSet(), name, out, parser.AllErrors); err != nil {
		t.Fatalf("parse %s as Go: %v\n--- output ---\n%s", name, err, out)
	}
	return out
}

// containsAll fails the test when any wanted substring is missing from
// got. Useful for asserting "the template emitted X, Y, and Z" without
// pinning down exact whitespace.
func containsAll(t *testing.T, name string, got []byte, wants ...string) {
	t.Helper()
	for _, w := range wants {
		if !strings.Contains(string(got), w) {
			t.Errorf("%s: missing %q\n--- got ---\n%s", name, w, got)
		}
	}
}

// =============================================================================
// rotini.gen.tmpl — the single framework template
// =============================================================================

// TestRender_rotiniGen pins the structural shape of the consolidated
// framework template. Each section the template emits (spec literal,
// inputs types + PopulateFromArgv, handler interfaces, lifecycle,
// executors, program, completion, render) gets a few representative
// substring checks. The intent is regression-coverage — if a section
// disappears or its signature drifts, this test trips.
func TestRender_rotiniGen(t *testing.T) {
	t.Parallel()
	in := internal.NewRenderInput("rotini", fixtureSpec())
	out := renderOK(t, "rotini.gen.tmpl", in)

	containsAll(t, "rotini.gen.tmpl", out,
		// Header.
		`// Code generated by rotini; DO NOT EDIT.`,
		`package rotini`,
		`"github.com/go-rotini/rotini/rtk"`,

		// Spec literal.
		`var Spec = rtk.ProgramSpec{`,
		`Name: "todo"`,
		`Identifiers: []string{"-o", "--output"}`,
		`Default: "table"`,
		`Path: "add"`,
		`Path: "foo-bar"`,
		`Required: true`,

		// Inputs types.
		`type RootFlags struct`,
		`Output  string`, // gofmt-aligned with Verbose bool below
		`Verbose bool`,
		`type RootInputs struct`,
		`func (i *RootInputs) RotiniCommandPath() string { return "" }`,
		`type AddFlags struct`,
		`Priority int`,
		`type AddArguments struct`,
		`Title string`,
		`type AddInputs struct`,
		`func (i *AddInputs) RotiniCommandPath() string { return "add" }`,
		`rtk.AssignFlag(scope, "output"`,
		`rtk.AssignFlag(scope, "priority"`,
		`rtk.AssignStringArg(r.ParsedArgs, 0`,
		`type FooBarFlags struct`,
		`Bopt int`,
		`type FooBarInputs struct`,
		"FooFlags "+" FooFlags", // field name + type; literal split to dodge dupword linter
		`func (i *FooBarInputs) RotiniCommandPath() string { return "foo-bar" }`,

		// Handler interfaces + Ctx aliases.
		`type RootCtx = rtk.Ctx`,
		`type RootHandler interface`,
		`Run(ctx RootCtx, inputs *RootInputs) error`,
		`type AddCtx = rtk.Ctx`,
		`type AddHandler interface`,
		`type FooBarCtx = rtk.Ctx`,
		`type FooBarHandler interface`,
		`type Handlers interface`,
		`Root() RootHandler`,
		`Add() AddHandler`,
		`FooBar() FooBarHandler`,

		// Lifecycle.
		`func SafeCall(fn func() error) (err error)`,
		`type Execution struct`,
		`Path string`,
		`Run  func() error`, // gofmt-aligned with Path string above
		`func RunExecution(ex Execution) error`,
		`var ErrEmptyExecution = errors.New(`,
		`var ErrParserUnbound = errors.New(`,

		// Executors.
		`var executors = map[string]func(*Program) Execution{`,
		`"":        buildRootExecution`,
		`"add":     buildAddExecution`,
		`"foo-bar": buildFooBarExecution`,
		`func buildRootExecution(p *Program) Execution`,
		`func buildAddExecution(p *Program) Execution`,
		`var inputs AddInputs`,
		`p.handlers.Add()`,

		// Program.
		`type Program struct`,
		`registry *rtk.Registry`,
		`handlers Handlers`,
		`func NewProgram(h Handlers) *Program`,
		`reg.Bind("io", rtk.NewIO())`,
		`reg.Bind("os", rtk.NewOS())`,
		`func (p *Program) Execute() error`,
		`func (p *Program) ExecuteArgs(argv []string) error`,
		`rtk.NewParser(Spec, rtk.Inputs{`,
		`rtk.Tokenize(argv, Spec)`,
		`RunExecution(build(p))`,

		// Completion.
		`func Completion(shell rtk.Shell) (string, error)`,
		`return rtk.GenerateCompletion(shell, Spec)`,

		// Render.
		`func RenderError(w io.Writer, err error)`,
		`func ExitCode(err error) int`,
		`"todo"`, // program name appears in the prefix initializer
		`rtk.UnknownCommandError`,
		`rtk.UnknownFlagError`,
		`rtk.MissingRequiredError`,
		`rtk.CoercionError`,
		`rtk.ValidationError`,
		`rtk.EarlyExit`,
	)
}

func TestRender_rotiniGen_emptyName(t *testing.T) {
	t.Parallel()
	in := internal.NewRenderInput("rotini", rtk.ProgramSpec{})
	out := renderOK(t, "rotini.gen.tmpl", in)
	// Empty Spec.Name renders; render() function body falls back to
	// the "rotini" string literal.
	containsAll(t, "rotini.gen.tmpl", out, `prefix := ""`, `"rotini"`)
}

func TestRender_rotiniGen_variadicArg(t *testing.T) {
	t.Parallel()
	// Variadic arguments use Type directly (translator sets "[]string"
	// for an `array` schema type), so the field renders as []string
	// and the assignment dispatches to AssignVariadicStringArg.
	spec := rtk.ProgramSpec{
		Name: "cat",
		Commands: []rtk.CommandSpec{
			{
				Path: "cat", Name: "cat",
				Arguments: []rtk.ArgumentSpec{
					{Name: "paths", Type: "[]string", Variadic: true},
				},
			},
		},
	}
	in := internal.NewRenderInput("rotini", spec)
	out := renderOK(t, "rotini.gen.tmpl", in)
	containsAll(t, "rotini.gen.tmpl", out,
		`Paths []string`,
		`rtk.AssignVariadicStringArg(r.ParsedArgs, 0`,
	)
}

func TestRender_rotiniGen_coercedArg(t *testing.T) {
	t.Parallel()
	spec := rtk.ProgramSpec{
		Name: "x",
		Commands: []rtk.CommandSpec{
			{
				Path: "count", Name: "count",
				Arguments: []rtk.ArgumentSpec{
					{Name: "n", Type: "int", Required: true},
				},
			},
		},
	}
	in := internal.NewRenderInput("rotini", spec)
	out := renderOK(t, "rotini.gen.tmpl", in)
	containsAll(t, "rotini.gen.tmpl", out,
		`N int`,
		`rtk.AssignCoercedArg(r.ParsedArgs, 0, "int", &i.Arguments.N, rtk.CoerceBuiltinValue)`,
	)
}

func TestRender_rotiniGen_ancestorComposition(t *testing.T) {
	t.Parallel()
	in := internal.NewRenderInput("rotini", fixtureSpec())
	out := renderOK(t, "rotini.gen.tmpl", in)
	// FooBarInputs.PopulateFromArgv must pull from root scope (""),
	// the "foo" intermediate scope, and the "bar" leaf scope.
	got := string(out)
	for _, want := range []string{
		`if scope := r.FlagsByScope[""]; scope != nil {`,
		`if scope := r.FlagsByScope["foo"]; scope != nil {`,
		`if scope := r.FlagsByScope["bar"]; scope != nil {`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("ancestor composition missing %q", want)
		}
	}
}

// =============================================================================
// handlers.go.tmpl — user's handlers package wiring
// =============================================================================

func TestRender_bridgeGen(t *testing.T) {
	t.Parallel()
	in := internal.NewRenderInput("cmd", fixtureSpec()).
		WithFramework("example.com/me/myapp/internal/cli/rotini", "rotini")
	out := renderOK(t, "handlers.go.tmpl", in)

	containsAll(t, "handlers.go.tmpl", out,
		`package cmd`,
		`rotini "example.com/me/myapp/internal/cli/rotini"`,
		`type handlers struct`,
		`func (h *handlers) Root() rotini.RootHandler { return h.root }`,
		`func (h *handlers) Add() rotini.AddHandler`,
		`func (h *handlers) FooBar() rotini.FooBarHandler`,
		`var Program = rotini.NewProgram(&handlers{`,
		`&RootHandlerImpl{}`,
		`&AddHandlerImpl{}`,
		`&FooBarHandlerImpl{}`,
	)
}

// =============================================================================
// handler.go.tmpl — per-command user-handler stubs
// =============================================================================

func TestRender_handlerSkelGen_root(t *testing.T) {
	t.Parallel()
	in := internal.NewRenderInput("cmd", fixtureSpec()).
		WithFramework("example.com/me/myapp/internal/cli/rotini", "rotini").
		WithCurrentPath("") // root command
	out := renderOK(t, "handler.go.tmpl", in)

	containsAll(t, "handler.go.tmpl", out,
		`package cmd`,
		`rotini "example.com/me/myapp/internal/cli/rotini"`,
		`type RootHandlerImpl struct{}`,
		`func (h *RootHandlerImpl) Run(`,
		`ctx rotini.RootCtx`,
		`inputs *rotini.RootInputs`,
		`// TODO: implement.`,
	)
}

func TestRender_handlerSkelGen_named(t *testing.T) {
	t.Parallel()
	in := internal.NewRenderInput("cmd", fixtureSpec()).
		WithFramework("example.com/me/myapp/internal/cli/rotini", "rotini").
		WithCurrentPath("foo-bar")
	out := renderOK(t, "handler.go.tmpl", in)

	containsAll(t, "handler.go.tmpl", out,
		`package cmd`,
		`rotini "example.com/me/myapp/internal/cli/rotini"`,
		`type FooBarHandlerImpl struct{}`,
		`func (h *FooBarHandlerImpl) Run(`,
		`ctx rotini.FooBarCtx`,
		`inputs *rotini.FooBarInputs`,
	)
}

// =============================================================================
// Unknown-template error
// =============================================================================

func TestRender_unknownTemplate(t *testing.T) {
	t.Parallel()
	in := internal.NewRenderInput("rotini", fixtureSpec())
	_, err := internal.Render("does-not-exist.tmpl", in)
	if err == nil {
		t.Fatal("expected error for unknown template, got nil")
	}
}

// =============================================================================
// Determinism — multiple renders produce identical output
// =============================================================================

// TestRender_deterministicOrdering verifies the framework template
// renders to byte-identical output across runs. Map iteration order
// in Go is randomized; sortedness of every iteration site is a hard
// requirement for byte-stable regen.
func TestRender_deterministicOrdering(t *testing.T) {
	t.Parallel()
	in := internal.NewRenderInput("rotini", fixtureSpec())
	for _, name := range []string{"rotini.gen.tmpl", "handlers.go.tmpl"} {
		a, err := internal.Render(name, in.WithFramework("example.com/x/y", "rotini"))
		if err != nil {
			t.Fatalf("first Render(%s): %v", name, err)
		}
		b, err := internal.Render(name, in.WithFramework("example.com/x/y", "rotini"))
		if err != nil {
			t.Fatalf("second Render(%s): %v", name, err)
		}
		if string(a) != string(b) {
			t.Errorf("%s: render is non-deterministic", name)
		}
	}
}
