// Code generated by jsonschema; DO NOT EDIT.

package internal

// Schema for a Rotini CLI configuration file.
type Conf struct {
	// URL identifying the rotini configuration schema version. The version segment must match the installed rotini binary version.
	Schema string `json:"$schema"`
	// Controls `rotini generate`: package targets and derived features. Omitted entirely → the defaults (merged single-file layout under internal/cmd/<root>, all features off).
	Generate *GenerateConfig `json:"generate,omitempty"`
	// Defaults for `rotini init`. Module-root confs ONLY — rejected by validation anywhere else (the block would be silently ignored).
	Initialize *InitializeConfig `json:"initialize,omitempty"`
	// Controls how `rotini validate` reports problems (collect everything vs. fail fast).
	Validate *ValidateConfig `json:"validate,omitempty"`
}

// A rendered/derived codegen feature: a toggle plus the output directory (under the cmdgen package) where its files live and are embedded.
type Feature struct {
	// How this feature's generated content is sourced into the cmdgen Go file. true: the rendered content is written to a file under 'dir' and the Go var is backed by a //go:embed directive. false (the default): no output file is written — the Go var is a hardcoded string literal holding the content inline, so the generated .go is self-contained. Var names and the resolver are identical either way.
	Embed bool `json:"embed,omitempty"`
	// Directory (relative to the module root) where this feature's rendered OUTPUT files (help_*.txt / man_*.txt / markdown_*.md / completion_<shell>.txt) are written in embed mode (embed: true) and sourced via //go:embed — so in embed mode it MUST resolve under the cmdgen package (//go:embed cannot reach outside it). In inline mode (embed: false) no output files are written and this is unused. Defaults to '<cmdgen-package>/renders'.
	EmbedDir string `json:"embed_dir,omitempty"`
	// When true, rotini generates this feature's outputs into the cmdgen package and emits the embed vars + resolver. Opt-in only.
	Enabled bool `json:"enabled,omitempty"`
	// Whether the editable rendering template (help.txt.tmpl / man.txt.tmpl / markdown.md.tmpl) is seeded into 'dir' for customization. true: the template is seeded when missing and pages render from it. false (the default): no template is seeded and pages render from rotini's built-in default. Ignored for completion (which has no template). A template you have already edited is never pruned — flipping this to false leaves it in place but inert.
	Template bool `json:"template,omitempty"`
	// Directory (relative to the module root) where this feature's editable rendering template (help.txt.tmpl / man.txt.tmpl / markdown.md.tmpl) is seeded when template: true. Templates are never //go:embed'd, so this is unconstrained — it may resolve anywhere. Ignored for completion (no template) and in template:false mode. Defaults to '<cmdgen-package>/templates'.
	TemplateDir string `json:"template_dir,omitempty"`
}

// Rendered/derived codegen features generated into the cmdgen (framework) package. Each shares one contract: a toggle (enabled), the var-sourcing strategy (embed: //go:embed a file in embed_dir vs an inline string literal), whether the editable rendering template is seeded (template, into template_dir), and a '<Prefix>' var + resolver in the cmdgen file. In embed mode embed_dir must resolve under the cmdgen package (//go:embed cannot reach outside it); inline features and template_dir have no such constraint. The two dirs default from the cmdgen package — embed_dir to '<cmdgen-package>/renders', template_dir to '<cmdgen-package>/templates'. Output files never collide: help pages are 'help_*.txt', man pages 'man_*.txt', markdown 'markdown_*.md', completion scripts 'completion_<shell>.txt', with pruning scoped to each feature's own files.
type FeaturesConfig struct {
	// Embedded shell completion scripts — the features group's exception: generated per supported shell (bash/zsh/fish/powershell) from the program name, not per command, with no doc-data, no editable template, and no verbatim escape. Emits 'Completion<Shell>' vars plus a 'Completion(shell string) (string, error)' resolver that a handler reads instead of building the script itself (`rotini init --wire completion` seeds exactly that handler). The scripts call the binary's hidden `__complete` entry, whose candidates are one per line, each optionally carrying a one-line description after a tab ('name\tdescription' — command/flag summaries ride automatically): zsh/fish/powershell render the description beside the name, bash strips it.
	Completion *Feature `json:"completion,omitempty"`
	// Embedded, per-command help text. When enabled, rotini produces a per-command help .txt for every command and embeds them in the cmdgen package as 'Help<Prefix>' string vars plus a 'Help(path ...string) (string, error)' resolver. Each .txt is rotini-managed: when a command sets a verbatim 'help' string in the spec it is written exactly; otherwise the page is rendered from the command's structured help fields (summary/description/usage/...) via the editable help template in the feature's dir.
	Help *Feature `json:"help,omitempty"`
	// Embedded, per-command man pages. Same render-or-verbatim contract as help: each command's .txt is rendered from its doc-fields through the editable man template in the feature's dir, or written verbatim when the command sets a 'man' string in the spec. Emits 'Man<Prefix>' vars plus a 'Man(path ...string) (string, error)' resolver.
	Man *Feature `json:"man,omitempty"`
	// Per-command reference markdown — the fourth doc feature, same render-or-verbatim contract as help/man: each command's .md is rendered from its doc-fields through the editable markdown template in the feature's dir ('markdown.md.tmpl'), or written verbatim when the command sets a 'markdown' string in the spec. Emits 'Markdown<Prefix>' vars plus a 'Markdown(path ...string) (string, error)' resolver; files are named 'markdown_*.md'. The build-time feedstock for a docs site — unlike help/man there is no wired command to serve it at run time.
	Markdown *Feature `json:"markdown,omitempty"`
}

// Controls `rotini generate`: where the generated code is written ('packages') and which derived doc/completion outputs are emitted ('features').
type GenerateConfig struct {
	// The derived codegen outputs (help/man/completion), each an opt-in toggle plus its rotini-managed embed directory.
	Features *FeaturesConfig `json:"features,omitempty"`
	// Where the generated code is written: the entrypoint main.go, the handler-logic package (cmd), and the generated-framework package (cmdgen).
	Packages *PackagesConfig `json:"packages,omitempty"`
}

// Defaults for `rotini init`, read ONLY from the .rotini.conf.* at the module root (beside go.mod). A project without such a conf gets rotini's built-in defaults; explicit `rotini init` flags override these. Declared in any conf that is NOT at the module root, the block would be silently ignored — rotini validation rejects it there.
type InitializeConfig struct {
	// Serialization for the spec/conf files scaffolded by `rotini init` when run without an explicit --format. Default "yaml".
	Format string `json:"format,omitempty"`
	// Directory under the module root where `rotini init` creates new CLIs (each new CLI becomes a Go package beneath it). Default "cmd".
	Package string `json:"package,omitempty"`
}

// One generated package target: the directory (import path relative to the module root) and the rotini-controlled file written into it. When 'cmd' and 'cmdgen' resolve to the same package AND file, the framework and the handler rollup are merged into that one file; when they differ in package, the rollup imports the framework. Rotini-managed files that no longer correspond to a command are pruned every pass; list package-relative paths under 'keep' to spare hand-written files.
type PackageConfig struct {
	// Bare name (no directory) of the rotini-controlled file written into the package; must end in .go. Defaults to 'zz_rotini.gen.go' (the entrypoint defaults to 'main.go').
	File string `json:"file,omitempty"`
	// Package-relative paths (e.g. 'helpers.go') that pruning must never remove, even when they do not correspond to a command in the spec. The editable per-feature templates and test files are always kept automatically. Intended to stay empty in steady state.
	Keep []string `json:"keep,omitempty"`
	// Import path (relative to the module root) of the target package; the Go package name is the last path segment. Defaults to 'internal/cmd/<root-command>'.
	Package string `json:"package,omitempty"`
}

// The generated package targets. 'cmd' holds the handler logic — the per-command stubs and the rollup (handlers struct, Program, Handlers()). 'cmdgen' holds the generated framework — the typed inputs, the definition, NewProgram — plus any enabled feature embeds (help/man/completion). Point both at the same package+file (the default) for one self-contained package, or at different packages to split the handler logic from the framework/types (so another package can import cmdgen's types for passthrough functions without an import cycle). 'entrypoint', when declared, is where generate writes the binary's main.go (create-once: never overwritten).
type PackagesConfig struct {
	// The handler-logic package: the per-command stubs and the rollup (handlers struct, Program, Handlers()).
	Cmd *PackageConfig `json:"cmd,omitempty"`
	// The generated-framework package: the typed inputs, the definition, NewProgram, plus any enabled feature embeds.
	Cmdgen *PackageConfig `json:"cmdgen,omitempty"`
	// Where generate writes the binary's main.go — create-once, never overwritten. 'package' is required for the entrypoint to be written; 'file' defaults to 'main.go' here (not the shared zz_rotini.gen.go default); 'keep' does not apply (the entrypoint package is never pruned).
	Entrypoint *PackageConfig `json:"entrypoint,omitempty"`
}

// Controls how `rotini validate` reports problems. Strictness is fixed (validation is always strict); only the failure-reporting mode is configurable. The `--fail` flag overrides this.
type ValidateConfig struct {
	// fast = stop at and report the first problem; collect = run to completion and report every problem at once (default).
	Fail string `json:"fail,omitempty"`
}
