// Code generated by jsonschema; DO NOT EDIT.

package internal

// Schema for a Rotini CLI definition spec file.
type Spec struct {
	// URL identifying the rotini spec schema version. The version segment must match the rotini binary version used.
	Schema string `json:"$schema"`
	// The CLI's root command. Same recursive Command shape as every sub-command (one type for the root and all sub-commands); the root must use 'name' (not '$ref'). Command-scoped concerns — doc-fields, inputs, sub-commands, remote commands — live here; program-scoped concerns (configuration_files, metadata, schemas) live at the document level beside it.
	Command Command `json:"command"`
	// Config-file sources the program loads at startup (document-level). Per-command 'config' inputs bind typed values from these by name + key.
	ConfigurationFiles []ConfigurationFile `json:"configuration_files,omitempty"`
	// Build-time metadata vars injected via go ldflags (document-level).
	Metadata []MetadataEntry `json:"metadata,omitempty"`
	// Reusable named schema definitions (document-level). Referenced elsewhere via "$ref": "#/schemas/<Name>".
	Schemas map[string]Schema `json:"schemas,omitempty"`
}

type ArgumentInput struct {
	// Deprecation message; the argument is annotated as deprecated in generated help.
	Deprecated string `json:"deprecated,omitempty"`
	// When true, the argument is omitted from generated help (it still parses on the command line).
	Hidden bool `json:"hidden,omitempty"`
	// Logical name for the argument
	Name string `json:"name"`
	// Type definition and input-level metadata (type, required, default, enum, nullable, constraints)
	Schema *InputSchema `json:"schema,omitempty"`
	// Short one-liner shown next to this argument in the Arguments section of generated help.
	Summary string `json:"summary,omitempty"`
}

// Shared fields for Schema and InputSchema. JSON Schema Draft 7 does not support additionalProperties: false on schemas that use allOf for inheritance — strictness is enforced by Go's DisallowUnknownFields at parse time.
type BaseSchema struct {
	// Reference to a named schema in the top-level schemas map (e.g. '#/schemas/MySchema'). Resolved at codegen time.
	Ref string `json:"$ref,omitempty"`
	// Allowed values; parsed values are validated against this list
	Enum []string `json:"enum,omitempty"`
	// Optional Go import path backing 'type'. Set it when 'type' references a stdlib or third-party package whose name rotini does not already know (e.g. 'github.com/google/uuid' for uuid.UUID; 'net/url' for *url.URL). Omit (or leave empty) for builtins and rotini's own type aliases (string, int, duration, …) — codegen treats omitted/empty as 'no import'. The aliased form 'alias path' renames the import to avoid a clash (e.g. 'urlx github.com/me/url'). Codegen dedupes identical entries across the spec.
	Import   string  `json:"import,omitempty"`
	Items    *Schema `json:"items,omitempty"`
	MaxItems int     `json:"maxItems,omitempty"`
	// Maximum string length (string type only)
	MaxLength int `json:"maxLength,omitempty"`
	// Maximum allowed value (numeric types only)
	Maximum  float64 `json:"maximum,omitempty"`
	MinItems int     `json:"minItems,omitempty"`
	// Minimum string length (string type only)
	MinLength int `json:"minLength,omitempty"`
	// Minimum allowed value (numeric types only)
	Minimum  float64 `json:"minimum,omitempty"`
	Nullable bool    `json:"nullable,omitempty"`
	// Regular expression the value must match (string type only)
	Pattern    string            `json:"pattern,omitempty"`
	Properties map[string]Schema `json:"properties,omitempty"`
	// The type used to parse and store the value. Accepts both Go type names (bool, int, float64, []string, duration, map) and JSON Schema standard names (boolean, integer, number, array, object) — both are equivalent. For a stdlib or third-party Go type (e.g. time.Time, uuid.UUID), set 'import' to the backing package path.
	Type string `json:"type,omitempty"`
}

// A command node in the CLI command tree — the root command and every sub-command share this recursive shape. Declared inline (with 'name') or composed from another spec file (with '$ref'). When used as the root (the top-level 'command'), it must use 'name'.
type Command struct {
	// Path to another rotini spec file whose root command is statically composed in as this sub-command. Relative to this spec file. When set, 'name' optionally overrides the grafted sub-command name. Not valid on the root command.
	Ref string `json:"$ref,omitempty"`
	// Additional names that invoke this command. Command aliases affect dispatch routing; use identifiers on flags for flag aliases.
	Aliases []string `json:"aliases,omitempty"`
	// Sub-commands of this command (inline or composed via $ref).
	Commands []Command `json:"commands,omitempty"`
	// Deprecation message; the command is annotated as deprecated in its parent's generated Commands list.
	Deprecated string `json:"deprecated,omitempty"`
	// Long description block shown atop this command's generated help page. Ignored when 'help' (verbatim) is set.
	Description string `json:"description,omitempty"`
	// Example command-line invocations, rendered one per line. Ignored when 'help' is set.
	Examples []string `json:"examples,omitempty"`
	// Text rendered at the bottom of the page. Ignored when 'help' is set.
	Footer string `json:"footer,omitempty"`
	// Group label for organizing this command under a heading in its parent's generated Commands list. Commands sharing a group are bucketed together; groups appear in the order their first member is declared. Ungrouped commands fall under the default Commands heading. Presentation-only.
	Group string `json:"group,omitempty"`
	// Text rendered above the description block. Ignored when 'help' is set.
	Header string `json:"header,omitempty"`
	// Section heading overrides for the generated page; sane defaults fill any unset heading. Ignored when 'help' is set.
	Headings *HelpHeadings `json:"headings,omitempty"`
	// Exact, verbatim help page for this command. When set, rotini writes it byte-for-byte (no rendering) and ignores the structured help fields (description/usage/header/footer/examples/headings); 'summary' is still used in the parent's Commands list. When unset, rotini generates the page from the structured fields.
	Help string `json:"help,omitempty"`
	// When true, the command is omitted from its parent's generated Commands list (it still dispatches on the command line).
	Hidden bool `json:"hidden,omitempty"`
	// Typed inputs for this command: flags, arguments, config values, env variables, and stdin.
	Inputs *Inputs `json:"inputs,omitempty"`
	// Exact, verbatim man page for this command (the man feature's per-command escape, mirroring 'help'). When set, rotini writes it byte-for-byte and ignores the structured doc-fields for the man page; when unset, the man page is rendered from those fields through the man template.
	Man string `json:"man,omitempty"`
	// Exact, verbatim markdown page for this command (the markdown feature's per-command escape, mirroring 'help'). When set, rotini writes it byte-for-byte and ignores the structured doc-fields for the markdown page; when unset, the markdown page is rendered from those fields through the markdown template.
	Markdown string `json:"markdown,omitempty"`
	// Command name used in routing. As the root command (the top-level 'command') this is the binary name and must be set — the root cannot use '$ref'.
	Name string `json:"name,omitempty"`
	// This command's output shape, as a JSON-schema type. rotini generates a typed '<Prefix>Output' Go struct (or a named-type alias when it is a '$ref' to a document-level schema) for the handler to use however it likes — it wires NO flag and triggers NO rendering. Handlers have no return type by design, so 'output' is an opt-in building block, never a framework-enforced contract.
	Output *Schema `json:"output,omitempty"`
	// Co-located remote binaries dispatched as first-class sub-commands of this command.
	RemoteCommands []RemoteCommandSpec `json:"remote_commands,omitempty"`
	// Auto-expose external '<prefix>*' executables as remote sub-commands of this command (kubectl/git/gh plugin discovery), in addition to any declared remote_commands. Presence enables discovery.
	RemoteDiscovery *RemoteDiscovery `json:"remote_discovery,omitempty"`
	// Short one-liner shown next to this command in its parent's generated Commands list. Applies even when a verbatim 'help' string is set, since it feeds the parent's list — not this command's own page.
	Summary string `json:"summary,omitempty"`
	// Not supported on a local command and rejected by rotini validation: a timeout is a remote-only, host-side bound on a dispatched binary, so it has no effect on local execution. Set it on a remote_commands[] entry's 'timeout' instead. (Recognized here only so validation can give that targeted error rather than a generic 'unknown property'.)
	Timeout string `json:"timeout,omitempty"`
	// Usage-line override. When omitted, rotini derives one from the command's shape. Ignored when 'help' is set.
	Usage string `json:"usage,omitempty"`
}

type ConfigInput struct {
	// Deprecation message; the input is annotated as deprecated in generated help.
	Deprecated string `json:"deprecated,omitempty"`
	// When true, the input is omitted from generated help (it is still bound).
	Hidden bool `json:"hidden,omitempty"`
	// Logical name for this config value
	Name string `json:"name"`
	// Type definition and input-level metadata (required, default, file, key)
	Schema *InputSchema `json:"schema,omitempty"`
	// Short one-liner shown next to this input in the generated Environment/Configuration help section.
	Summary string `json:"summary,omitempty"`
}

type ConfigurationFile struct {
	// File format
	Format string `json:"format,omitempty"`
	// Logical name for the config file (e.g., 'app-config')
	Name string `json:"name"`
	// File path (supports ~ for home dir)
	Path string `json:"path"`
	// When set, generates a typed config struct and validates required fields at load time.
	Schema *Schema `json:"schema,omitempty"`
}

type EnvInput struct {
	// Deprecation message; the input is annotated as deprecated in generated help.
	Deprecated string `json:"deprecated,omitempty"`
	// When true, the input is omitted from generated help (it is still bound).
	Hidden bool `json:"hidden,omitempty"`
	// Logical name for this env var input
	Name string `json:"name"`
	// Type definition and input-level metadata (required, default, variable)
	Schema *InputSchema `json:"schema,omitempty"`
	// Short one-liner shown next to this input in the generated Environment/Configuration help section.
	Summary string `json:"summary,omitempty"`
}

// A conditional requirement: when the 'when' flag is explicitly set on the command line, every flag in 'requires' must also be set. Both reference flag logical names; 'set' means explicitly provided (a default or env/config fallback does not count).
type FlagDependency struct {
	// Flags that must also be set when 'when' is set.
	Requires []string `json:"requires"`
	// The flag whose presence triggers the requirement.
	When string `json:"when"`
}

// A constraint on which of this command's flags may (or must) be set together. 'flags' references flag logical names; 'set' means explicitly provided on the command line (a default or env/config fallback does not count).
type FlagGroup struct {
	Flags []string `json:"flags"`
	// mutually_exclusive: at most one set. required_together: all or none. one_of: exactly one. at_least_one: one or more.
	Kind string `json:"kind"`
}

type FlagInput struct {
	// When true, this flag is advertised in the generated help of every descendant command (under the 'Global Flags' section), not only on its own command. Display-only: all flags already resolve up the command chain at runtime regardless of this setting; cascading controls whether descendants document it.
	Cascading bool `json:"cascading,omitempty"`
	// Deprecation message; the flag is annotated as deprecated in generated help.
	Deprecated string `json:"deprecated,omitempty"`
	// When true, the flag is omitted from generated help (it still parses on the command line).
	Hidden bool `json:"hidden,omitempty"`
	// CLI flag identifiers (e.g., '--force', '-f'). When absent, '--<name>' is auto-derived.
	Identifiers []string `json:"identifiers,omitempty"`
	// Logical name for the flag
	Name string `json:"name"`
	// Type definition and input-level metadata (type, required, default, enum, nullable, constraints)
	Schema *InputSchema `json:"schema,omitempty"`
	// Short one-liner shown next to this flag in the Flags section of generated help.
	Summary string `json:"summary,omitempty"`
}

// Section heading overrides for generated help pages.
type HelpHeadings struct {
	Arguments string `json:"arguments,omitempty"`
	// Heading for the cascading-flags section on descendant pages. Defaults to 'Global Flags:'. The value is rendered verbatim, so include a trailing ':' if you want one.
	Cascading     string `json:"cascading,omitempty"`
	Commands      string `json:"commands,omitempty"`
	Configuration string `json:"configuration,omitempty"`
	Environment   string `json:"environment,omitempty"`
	Examples      string `json:"examples,omitempty"`
	Flags         string `json:"flags,omitempty"`
	Usage         string `json:"usage,omitempty"`
}

// Extended schema for input definitions (flags, arguments, env vars, config values, stdin). Inherits all BaseSchema fields and adds input-level metadata. The 'required' field here is a boolean indicating whether this input must be provided — unlike Schema where 'required' is a string array of property names.
type InputSchema struct {
	BaseSchema
	// Default value applied when the input is not provided
	Default any `json:"default,omitempty"`
	// Config file logical name to read from (config inputs only)
	File string `json:"file,omitempty"`
	// Key path within the config file (config inputs only, e.g., 'server.port')
	Key string `json:"key,omitempty"`
	// When true, the input must be provided (or stdin must not be empty for stdin inputs). Note: this is a boolean — unlike the string-array 'required' on Schema.
	Required bool `json:"required,omitempty"`
	// When true, this input's value is treated as a secret: redacted in provenance/error output by the default binder. Maps to recon's 'secret' tag.
	Secret bool `json:"secret,omitempty"`
	// Environment variable name (env inputs only)
	Variable string `json:"variable,omitempty"`
}

type Inputs struct {
	// Positional argument inputs for this command
	Arguments []ArgumentInput `json:"arguments,omitempty"`
	// Config-value inputs for this command, bound from a document-level configuration_files source by key.
	Config []ConfigInput `json:"config,omitempty"`
	// Environment-variable inputs for this command
	Env []EnvInput `json:"env,omitempty"`
	// Conditional cross-flag requirements validated at parse time: when one flag is set, others become required (e.g. when --tls is set, --cert and --key are required).
	FlagDependencies []FlagDependency `json:"flag_dependencies,omitempty"`
	// Cross-flag presence rules validated at parse time (e.g. mutually exclusive output formats, a required-together credential pair).
	FlagGroups []FlagGroup `json:"flag_groups,omitempty"`
	// Flag inputs for this command
	Flags []FlagInput `json:"flags,omitempty"`
	// Declares expected stdin format and schema for this command
	Stdin *StdinSpec `json:"stdin,omitempty"`
}

type MetadataEntry struct {
	// Fallback value used when the ldflag has not been applied at build time. Becomes the var's initial value in the generated file.
	Default string `json:"default,omitempty"`
	// Exported Go identifier for the ldflag var. Rotini declares this as a package-level var in the framework package. Inject at build time: -ldflags "-X <module>/<framework-pkg>.<var>=<value>"
	Var string `json:"var"`
}

type RemoteCommandSpec struct {
	// Additional names that invoke this remote command.
	Aliases []string `json:"aliases,omitempty"`
	// Long description block for this remote command's generated help page.
	Description string `json:"description,omitempty"`
	// Name of the remote command. The dispatched binary must be named <program>-<name> and located in the same directory as the host binary.
	Name string `json:"name"`
	// Short one-liner shown next to this remote command in its parent's generated Commands list.
	Summary string `json:"summary,omitempty"`
	// Host-side timeout for the remote binary execution. Uses Go duration format (e.g. "10s", "1m30s"). Empty or omitted means no timeout.
	Timeout string `json:"timeout,omitempty"`
}

// Auto-expose external '<prefix>*' executables as remote sub-commands (kubectl/git/gh plugin style), alongside any declared remote_commands. Presence enables discovery; a discovered name that collides with a declared command or remote is skipped.
type RemoteDiscovery struct {
	// When true, discovered plugins still dispatch but are omitted from completion listings.
	Hidden bool `json:"hidden,omitempty"`
	// Extra directory to scan for plugins, in addition to the host binary's directory and PATH.
	Path string `json:"path,omitempty"`
	// Executable-name prefix to discover. Default: the host binary name followed by '-' (e.g. 'acme-').
	Prefix string `json:"prefix,omitempty"`
}

// JSON Schema-inspired type definition used for output/response and object property schemas. The 'required' field is a string array of required property names (JSON Schema object semantics). For input schemas where 'required' means 'must be provided', use InputSchema instead.
type Schema struct {
	BaseSchema
	// Required property names for object schemas (standard JSON Schema semantics).
	Required []string `json:"required,omitempty"`
}

type StdinSpec struct {
	// Serialization the piped stdin payload is decoded from (into the generated <Prefix>Stdin type). Defaults to json.
	Format string `json:"format,omitempty"`
	// Type definition for stdin content. Set required: true in schema to error when stdin is empty.
	Schema *InputSchema `json:"schema,omitempty"`
}
