// Code generated by jsonschema; DO NOT EDIT.

package internal

// Schema for a Rotini CLI definition spec file.
type Spec struct {
	// URL identifying the rotini spec schema version. The version segment must match the installed rotini binary version.
	Schema string `json:"$schema"`
	// Additional names that invoke the root command.
	Aliases []string `json:"aliases,omitempty"`
	// Sub-commands of the root command.
	Commands []Command `json:"commands,omitempty"`
	// Events this program can emit. Each name must be unique.
	Events []EventSpec `json:"events,omitempty"`
	// Config files to load at startup.
	Files []ConfigSpec `json:"files,omitempty"`
	// Typed inputs for the root command: flags, arguments, file values, and variables.
	Inputs *Inputs `json:"inputs,omitempty"`
	// Build-time metadata vars injected via go ldflags.
	Metadata []MetadataEntry `json:"metadata,omitempty"`
	// Root command name used in routing.
	Name string `json:"name"`
	// Co-located remote binaries dispatched as first-class sub-commands of the root command.
	RemoteCommands []RemoteCommandSpec `json:"remote_commands,omitempty"`
	// Reusable named schema definitions. Referenced elsewhere via "$ref": "#/schemas/<Name>".
	Schemas map[string]Schema `json:"schemas,omitempty"`
	// Root command execution timeout. Uses Go duration format (e.g. "10s", "1m30s"). Empty or omitted means no timeout.
	Timeout string `json:"timeout,omitempty"`
}

type ArgumentInput struct {
	// Logical name for the argument
	Name string `json:"name"`
	// Type definition and input-level metadata (required, deprecated, default)
	Schema *InputSchema `json:"schema,omitempty"`
}

// Shared fields for Schema and InputSchema. JSON Schema Draft 7 does not support additionalProperties: false on schemas that use allOf for inheritance — strictness is enforced by Go's DisallowUnknownFields at parse time.
type BaseSchema struct {
	// Reference to a named schema in the top-level schemas map (e.g. '#/schemas/MySchema'). Resolved at codegen time.
	Ref         string `json:"$ref,omitempty"`
	Description string `json:"description,omitempty"`
	// Allowed values; parsed values are validated against this list
	Enum     []string `json:"enum,omitempty"`
	Items    *Schema  `json:"items,omitempty"`
	MaxItems int      `json:"maxItems,omitempty"`
	// Maximum string length (string type only)
	MaxLength int `json:"maxLength,omitempty"`
	// Maximum allowed value (numeric types only)
	Maximum  float64 `json:"maximum,omitempty"`
	MinItems int     `json:"minItems,omitempty"`
	// Minimum string length (string type only)
	MinLength int `json:"minLength,omitempty"`
	// Minimum allowed value (numeric types only)
	Minimum  float64 `json:"minimum,omitempty"`
	Nullable bool    `json:"nullable,omitempty"`
	// Regular expression the value must match (string type only)
	Pattern    string            `json:"pattern,omitempty"`
	Properties map[string]Schema `json:"properties,omitempty"`
	// The type used to parse and store the value. Accepts both Go type names (bool, int, float64, []string, duration, map) and JSON Schema standard names (boolean, integer, number, array, object) — both are equivalent.
	Type string `json:"type,omitempty"`
}

// A command node in the CLI command tree. A command is either declared inline (with 'name') or composed from another spec file (with '$ref').
type Command struct {
	// Path to another rotini spec file whose command tree is statically composed in as this sub-command. Relative to this spec file. When set, 'name' optionally overrides the grafted sub-command name.
	Ref string `json:"$ref,omitempty"`
	// Additional names that invoke this command. Command aliases affect dispatch routing; use identifiers on flags for flag aliases.
	Aliases []string `json:"aliases,omitempty"`
	// Sub-commands of this command.
	Commands []Command `json:"commands,omitempty"`
	// Typed inputs for this command: flags, arguments, file values, and variables.
	Inputs *Inputs `json:"inputs,omitempty"`
	// Command name used in routing.
	Name string `json:"name,omitempty"`
	// Co-located remote binaries dispatched as first-class sub-commands of this command.
	RemoteCommands []RemoteCommandSpec `json:"remote_commands,omitempty"`
	// Command execution timeout. Uses Go duration format (e.g. "10s", "1m30s"). Empty or omitted means no timeout.
	Timeout string `json:"timeout,omitempty"`
}

type ConfigInput struct {
	// Logical name for this config value
	Name string `json:"name"`
	// Type definition and input-level metadata (required, default, file, key)
	Schema *InputSchema `json:"schema,omitempty"`
}

type ConfigSpec struct {
	// File format
	Format string `json:"format,omitempty"`
	// Logical name for the config file (e.g., 'app-config')
	Name string `json:"name"`
	// File path (supports ~ for home dir)
	Path string `json:"path"`
	// When set, generates a typed config struct and validates required fields at load time.
	Schema *Schema `json:"schema,omitempty"`
}

type EnvInput struct {
	// Logical name for this env var input
	Name string `json:"name"`
	// Type definition and input-level metadata (required, default, variable)
	Schema *InputSchema `json:"schema,omitempty"`
}

type EventSpec struct {
	// Unique event name (snake_case). Used to name Emit{Name} methods and On{Name} handler fields.
	Name string `json:"name"`
	// Shape of the event payload. When omitted, the emit method takes a *{BinName}{PascalName}EventMsg of an empty struct.
	Schema *Schema `json:"schema,omitempty"`
}

type FlagInput struct {
	// CLI flag identifiers (e.g., '--force', '-f'). When absent, '--<name>' is auto-derived.
	Identifiers []string `json:"identifiers,omitempty"`
	// Logical name for the flag
	Name string `json:"name"`
	// Type definition and input-level metadata (required, deprecated, default, hidden)
	Schema *InputSchema `json:"schema,omitempty"`
}

// Extended schema for input definitions (flags, arguments, env vars, config values, stdin). Inherits all BaseSchema fields and adds input-level metadata. The 'required' field here is a boolean indicating whether this input must be provided — unlike Schema where 'required' is a string array of property names.
type InputSchema struct {
	BaseSchema
	// Default value applied when the input is not provided
	Default any `json:"default,omitempty"`
	// Config file logical name to read from (config_values inputs only)
	File string `json:"file,omitempty"`
	// Key path within the config file (config_values inputs only, e.g., 'server.port')
	Key string `json:"key,omitempty"`
	// When true, the input must be provided (or stdin must not be empty for stdin inputs). Note: this is a boolean — unlike the string-array 'required' on Schema.
	Required bool `json:"required,omitempty"`
	// Environment variable name (environment inputs only)
	Variable string `json:"variable,omitempty"`
}

type Inputs struct {
	// Positional argument inputs for this command
	Arguments []ArgumentInput `json:"arguments,omitempty"`
	// Config file value inputs for this command
	Files []ConfigInput `json:"files,omitempty"`
	// Flag inputs for this command
	Flags []FlagInput `json:"flags,omitempty"`
	// Declares expected stdin format and schema for this command
	Stdin *StdinSpec `json:"stdin,omitempty"`
	// Environment variable inputs for this command
	Variables []EnvInput `json:"variables,omitempty"`
}

type MetadataEntry struct {
	// Fallback value used when the ldflag has not been applied at build time. Becomes the var's initial value in the generated file.
	Default string `json:"default,omitempty"`
	// Exported Go identifier for the ldflag var. Rotini declares this as a package-level var in the framework package. Inject at build time: -ldflags "-X <module>/<framework-pkg>.<var>=<value>"
	Var string `json:"var"`
}

type RemoteCommandSpec struct {
	// Additional names that invoke this remote command.
	Aliases []string `json:"aliases,omitempty"`
	// Name of the remote command. The dispatched binary must be named <program>-<name> and located in the same directory as the host binary.
	Name string `json:"name"`
	// Host-side timeout for the remote binary execution. Uses Go duration format (e.g. "10s", "1m30s"). Empty or omitted means no timeout.
	Timeout string `json:"timeout,omitempty"`
}

// JSON Schema-inspired type definition used for output/response and object property schemas. The 'required' field is a string array of required property names (JSON Schema object semantics). For input schemas where 'required' means 'must be provided', use InputSchema instead.
type Schema struct {
	BaseSchema
	// Required property names for object schemas (standard JSON Schema semantics).
	Required []string `json:"required,omitempty"`
}

type StdinSpec struct {
	// Type definition for stdin content. Set required: true in schema to error when stdin is empty.
	Schema *InputSchema `json:"schema,omitempty"`
}
