// Code generated by rotini; DO NOT EDIT.
package rotini

import "github.com/go-rotini/rotini/rtk"

// RootCtx is the [rtk.Ctx] alias for root-command handlers.
type RootCtx = rtk.Ctx

// RootHandler is the interface a root-command handler implementation
// satisfies. The framework calls Run after [RootInputs] has been
// populated from argv / env / config.
type RootHandler interface {
	Run(ctx RootCtx, inputs *RootInputs) error
}

// Handlers is the aggregate interface the user's handlers package
// satisfies. Each accessor returns the per-command handler the
// framework dispatches to. Codegen emits a default implementation in
// the user's `internal/handlers` package; users replace the bodies of
// the per-command Run methods to implement their CLI.
type Handlers interface {
	Root() RootHandler
}
