// Code generated by rotini; DO NOT EDIT.
package rotini

import "github.com/go-rotini/rotini/rtk"

// RootFlags carries the root command's program-level flags. Each
// sub-command's Inputs type composes RootFlags so handlers see the
// inherited program scope alongside their own.
type RootFlags struct {
	Name string
}

// RootInputs is the typed input for invocations of the root command
// (no sub-command supplied).
type RootInputs struct {
	Flags RootFlags
}

// RotiniCommandPath returns the empty string for the root command.
func (i *RootInputs) RotiniCommandPath() string { return "" }

// PopulateFromArgv reads parsed root-scope flag values into i.
func (i *RootInputs) PopulateFromArgv(r *rtk.Result) error {
	if scope := r.FlagsByScope[""]; scope != nil {
		rtk.AssignFlag(scope, "name", &i.Flags.Name)
	}
	_ = r
	return nil
}
