// Code generated by rotini; DO NOT EDIT.
package rotini

import (
	"errors"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/go-rotini/rotini/rtk"
)

// =============================================================================
// Spec
// =============================================================================

// Spec is the resolved program specification. The rotini framework
// consults it to drive argv tokenization, env/config fallback, and
// validation before each handler runs. Regenerate by re-running
// `go tool rotini generate` against the project's .rotini.spec.yaml.
var Spec = rtk.ProgramSpec{
	Name: "greet",
	Flags: []rtk.FlagSpec{
		{Name: "name", Identifiers: []string{"-n", "--name"}, Type: "string", Default: "world"},
	},
}

// =============================================================================
// Inputs — per-command Flags / Arguments / Inputs types + PopulateFromArgv
// =============================================================================

// RootFlags carries the root command's program-level flags. Each
// sub-command's Inputs type composes RootFlags so handlers see the
// inherited program scope alongside their own.
type RootFlags struct {
	Name string
}

// RootInputs is the typed input for invocations of the root command
// (no sub-command supplied).
type RootInputs struct {
	Flags RootFlags
}

// RotiniCommandPath returns the empty string for the root command.
func (i *RootInputs) RotiniCommandPath() string { return "" }

// PopulateFromArgv reads parsed root-scope flag values into i.
func (i *RootInputs) PopulateFromArgv(r *rtk.Result) error {
	if scope := r.FlagsByScope[""]; scope != nil {
		rtk.AssignFlag(scope, "name", &i.Flags.Name)
	}
	_ = r
	return nil
}

// =============================================================================
// Handler interfaces + Ctx aliases + aggregate Handlers interface
// =============================================================================

// RootCtx is the [rtk.Ctx] alias for root-command handlers.
type RootCtx = rtk.Ctx

// RootHandler is the interface a root-command handler implementation
// satisfies. The framework calls Run after [RootInputs] has been
// populated from argv / env / config.
type RootHandler interface {
	Run(ctx RootCtx, inputs *RootInputs) error
}

// Handlers is the aggregate interface the user's handlers package
// satisfies. Each accessor returns the per-command handler the
// framework dispatches to.
type Handlers interface {
	Root() RootHandler
}

// =============================================================================
// Lifecycle — SafeCall, Execution, RunExecution
// =============================================================================

// SafeCall wraps fn in a deferred recover() so a handler panic does
// not take down the entire process. Returns fn's error verbatim on
// normal return; converts panics into wrapped errors. *rtk.EarlyExit
// panics are preserved through the error chain so main()'s ExitCode()
// can pick up the requested exit code.
func SafeCall(fn func() error) (err error) {
	defer func() {
		if r := recover(); r != nil {
			if ee, ok := r.(*rtk.EarlyExit); ok {
				err = ee
				return
			}
			err = fmt.Errorf("rotini: handler panicked: %v", r)
		}
	}()
	return fn()
}

// Execution is the unit of dispatch a [Program] runs. It carries the
// matched command path and the closure that, when called, parses
// inputs and invokes the user's handler.
type Execution struct {
	Path string
	Run  func() error
}

// RunExecution invokes ex.Run wrapped in [SafeCall]. Returns
// [ErrEmptyExecution] when ex.Run is nil — a codegen bug rather than
// a user-input error.
func RunExecution(ex Execution) error {
	if ex.Run == nil {
		return ErrEmptyExecution
	}
	return SafeCall(ex.Run)
}

// ErrEmptyExecution indicates an Execution with no Run closure was
// dispatched. Always a generated-code bug.
var ErrEmptyExecution = errors.New("rotini: execution has nil Run closure")

// ErrParserUnbound is returned when an Execution closure runs but no
// Parser service is bound under the "parser" registry key. Always a
// generated-code bug.
var ErrParserUnbound = errors.New("rotini: parser service not bound")

// =============================================================================
// Executors — per-command Execution builders + dispatch map
// =============================================================================

// executors is the per-command-path dispatch map. [Program.Execute]
// looks up the matched command path and invokes the resulting
// [Execution] under [SafeCall].
var executors = map[string]func(*Program) Execution{
	"": buildRootExecution,
}

// buildRootExecution builds the [Execution] for the root command.
func buildRootExecution(p *Program) Execution {
	return Execution{
		Path: "",
		Run: func() error {
			parser := rtk.Get[rtk.Parser](p.registry, "parser")
			if parser == nil {
				return ErrParserUnbound
			}
			var inputs RootInputs
			if err := parser.Parse(&inputs); err != nil {
				return err
			}
			return p.handlers.Root().Run(rtk.Ctx{Registry: p.registry}, &inputs)
		},
	}
}

// =============================================================================
// Program — entrypoint type + NewProgram + Execute auto-binding rtk services
// =============================================================================

// Program is the assembled CLI. Construct via [NewProgram], then call
// [Program.Execute] from main().
type Program struct {
	registry *rtk.Registry
	handlers Handlers
}

// NewProgram returns a Program wired with the supplied Handlers and
// the rtk-default services (IO, OS, Signals, Ticker) bound under the
// well-known keys "io", "os", "signals", "ticker".
func NewProgram(h Handlers) *Program {
	reg := rtk.NewRegistry()
	reg.Bind("io", rtk.NewIO())
	reg.Bind("os", rtk.NewOS())
	reg.Bind("signals", rtk.NewSignals())
	reg.Bind("ticker", rtk.NewTicker())
	return &Program{registry: reg, handlers: h}
}

// Registry returns the program's service registry. Callers can bind
// overrides (e.g., for tests) before calling Execute.
func (p *Program) Registry() *rtk.Registry { return p.registry }

// Execute parses os.Args[1:] and dispatches to the matched command's
// handler. Returns the handler's error verbatim — rtk error types
// such as *EarlyExit propagate through so main()'s ExitCode mapping
// can act on them.
func (p *Program) Execute() error {
	return p.ExecuteArgs(os.Args[1:])
}

// ExecuteArgs is the testable form of [Program.Execute]: argv is
// supplied explicitly so tests don't have to mutate os.Args.
func (p *Program) ExecuteArgs(argv []string) error {
	ros := rtk.Get[rtk.OS](p.registry, "os")
	if ros == nil {
		ros = rtk.NewOS()
	}
	parser := rtk.NewParser(Spec, rtk.Inputs{
		Argv:  argv,
		Stdin: os.Stdin,
		Env:   ros,
	})
	p.registry.Bind("parser", parser)

	tok, err := rtk.Tokenize(argv, Spec)
	if err != nil {
		return err
	}
	path := strings.Join(tok.CommandPath, "-")

	build, ok := executors[path]
	if !ok {
		return errors.New("rotini: no executor for command path " + path)
	}
	return RunExecution(build(p))
}

// =============================================================================
// Completion — per-program accessor wrapping rtk.GenerateCompletion
// =============================================================================

// Completion returns a shell-completion script for the program's
// spec. shell is one of [rtk.SupportedShells]. Returns
// [rtk.ErrUnknownShell] for an unrecognized shell name.
func Completion(shell rtk.Shell) (string, error) {
	return rtk.GenerateCompletion(shell, Spec)
}

// =============================================================================
// Render — RenderError + ExitCode
// =============================================================================

// RenderError writes a human-readable representation of err to w.
// Recognized rtk error types get a brief category prefix so users
// can tell at a glance what kind of failure occurred.
func RenderError(w io.Writer, err error) {
	if w == nil || err == nil {
		return
	}
	prefix := "greet"
	if prefix == "" {
		prefix = "rotini"
	}

	var (
		unkCmd *rtk.UnknownCommandError
		unkFlg *rtk.UnknownFlagError
		unkArg *rtk.UnknownArgumentError
		missR  *rtk.MissingRequiredError
		coerce *rtk.CoercionError
		valid  *rtk.ValidationError
	)
	switch {
	case errors.As(err, &unkCmd):
		fmt.Fprintf(w, "%s: unknown command: %s\n", prefix, unkCmd.Error())
	case errors.As(err, &unkFlg):
		fmt.Fprintf(w, "%s: unknown flag: %s\n", prefix, unkFlg.Error())
	case errors.As(err, &unkArg):
		fmt.Fprintf(w, "%s: %s\n", prefix, unkArg.Error())
	case errors.As(err, &missR):
		fmt.Fprintf(w, "%s: %s\n", prefix, missR.Error())
	case errors.As(err, &coerce):
		fmt.Fprintf(w, "%s: %s\n", prefix, coerce.Error())
	case errors.As(err, &valid):
		fmt.Fprintf(w, "%s: %s\n", prefix, valid.Error())
	default:
		fmt.Fprintf(w, "%s: %s\n", prefix, err.Error())
	}
}

// ExitCode maps an error to a process exit code suitable for os.Exit.
// nil → 0. *rtk.EarlyExit carries an explicit code through. Anything
// else returns 1.
func ExitCode(err error) int {
	if err == nil {
		return 0
	}
	var ee *rtk.EarlyExit
	if errors.As(err, &ee) {
		return ee.Code
	}
	return 1
}
