// Code generated by rotini; DO NOT EDIT.
package rotini

import "github.com/go-rotini/rotini/rtk"

// Spec is the resolved program specification. The rotini framework
// consults it to drive argv tokenization, env/config fallback, and
// validation before each handler runs. Regenerate by re-running
// `go tool rotini generate` against the project's .rotini.spec.yaml.
var Spec = rtk.ProgramSpec{
	Name: "greet",
	Flags: []rtk.FlagSpec{
		{Name: "name", Identifiers: []string{"-n", "--name"}, Type: "string", Default: "world"},
	},
}
