// Code generated by rotini; DO NOT EDIT.
package handlers

import rotini "github.com/go-rotini/rotini/internal/rotini"

// handlers is the assembled bag of per-command handler
// implementations the framework dispatches to. Each field holds a
// pointer to the user-authored *HandlerImpl type for one command.
//
// Per-command accessor methods satisfy the framework's
// rotini.Handlers interface so the framework can
// retrieve any handler by command-path without depending on the
// concrete handler types.
type handlers struct {
	root       *RootHandlerImpl
	completion *CompletionHandlerImpl
	generate   *GenerateHandlerImpl
	help       *HelpHandlerImpl
	initialize *InitializeHandlerImpl
	validate   *ValidateHandlerImpl
	version    *VersionHandlerImpl
}

// Root returns the user's root-command handler.
func (h *handlers) Root() rotini.RootHandler { return h.root }

// Completion returns the user's "completion" command handler.
func (h *handlers) Completion() rotini.CompletionHandler { return h.completion }

// Generate returns the user's "generate" command handler.
func (h *handlers) Generate() rotini.GenerateHandler { return h.generate }

// Help returns the user's "help" command handler.
func (h *handlers) Help() rotini.HelpHandler { return h.help }

// Initialize returns the user's "initialize" command handler.
func (h *handlers) Initialize() rotini.InitializeHandler { return h.initialize }

// Validate returns the user's "validate" command handler.
func (h *handlers) Validate() rotini.ValidateHandler { return h.validate }

// Version returns the user's "version" command handler.
func (h *handlers) Version() rotini.VersionHandler { return h.version }

// Program is the assembled CLI ready to call .Execute() in main().
//
//	func main() {
//	    os.Exit(rotini.ExitCode(handlers.Program.Execute()))
//	}
var Program = rotini.NewProgram(&handlers{
	root:       &RootHandlerImpl{},
	completion: &CompletionHandlerImpl{},
	generate:   &GenerateHandlerImpl{},
	help:       &HelpHandlerImpl{},
	initialize: &InitializeHandlerImpl{},
	validate:   &ValidateHandlerImpl{},
	version:    &VersionHandlerImpl{},
})
