// Code generated by rotini; DO NOT EDIT.
package rotini

import "github.com/go-rotini/rotini/rtk"

// RootFlags carries the root command's program-level flags. Each
// sub-command's Inputs type composes RootFlags so handlers see the
// inherited program scope alongside their own.
type RootFlags struct {
}

// RootInputs is the typed input for invocations of the root command
// (no sub-command supplied).
type RootInputs struct {
	Flags RootFlags
}

// RotiniCommandPath returns the empty string for the root command.
func (i *RootInputs) RotiniCommandPath() string { return "" }

// PopulateFromArgv reads parsed root-scope flag values into i.
func (i *RootInputs) PopulateFromArgv(r *rtk.Result) error {
	_ = r
	return nil
}

// SendFlags carries the "send" command's own flags.
type SendFlags struct {
}

// SendInputs is the typed input for the "send" command.
// It composes the root program-level flags (RootFlags) plus the
// command's own flags and positional arguments. Intermediate-ancestor
// flag scopes are exposed under per-segment fields.
type SendInputs struct {
	RootFlags RootFlags
	Flags     SendFlags
}

// RotiniCommandPath returns the hyphen-joined command path "send".
func (i *SendInputs) RotiniCommandPath() string { return "send" }

// PopulateFromArgv reads parsed flag and argument values into i.
func (i *SendInputs) PopulateFromArgv(r *rtk.Result) error {
	_ = r
	return nil
}
