// Code generated by rotini; DO NOT EDIT.
package rotini

import (
	"errors"
	"fmt"
	"io"

	"github.com/go-rotini/rotini/rtk"
)

// RenderError writes a human-readable representation of err to w. It is
// intended for main()-level error reporting: parse failures, validation
// failures, and any other error a handler returns.
//
// The default format is `<program>: <error>`. Recognized rtk error
// types get a brief category prefix so users can tell at a glance
// whether the failure was a flag typo (UnknownFlagError), a missing
// required input (MissingRequiredError), a coercion problem
// (CoercionError), or something else.
func RenderError(w io.Writer, err error) {
	if w == nil || err == nil {
		return
	}
	prefix := "mailer"
	if prefix == "" {
		prefix = "rotini"
	}

	var (
		unkCmd *rtk.UnknownCommandError
		unkFlg *rtk.UnknownFlagError
		unkArg *rtk.UnknownArgumentError
		missR  *rtk.MissingRequiredError
		coerce *rtk.CoercionError
		valid  *rtk.ValidationError
	)
	switch {
	case errors.As(err, &unkCmd):
		fmt.Fprintf(w, "%s: unknown command: %s\n", prefix, unkCmd.Error())
	case errors.As(err, &unkFlg):
		fmt.Fprintf(w, "%s: unknown flag: %s\n", prefix, unkFlg.Error())
	case errors.As(err, &unkArg):
		fmt.Fprintf(w, "%s: %s\n", prefix, unkArg.Error())
	case errors.As(err, &missR):
		fmt.Fprintf(w, "%s: %s\n", prefix, missR.Error())
	case errors.As(err, &coerce):
		fmt.Fprintf(w, "%s: %s\n", prefix, coerce.Error())
	case errors.As(err, &valid):
		fmt.Fprintf(w, "%s: %s\n", prefix, valid.Error())
	default:
		fmt.Fprintf(w, "%s: %s\n", prefix, err.Error())
	}
}

// ExitCode maps an error to a process exit code suitable for os.Exit.
// nil → 0. *rtk.EarlyExit carries an explicit code through. Anything
// else returns 1.
//
// Generated code calls ExitCode in main() — `os.Exit(ExitCode(err))` —
// so handlers can short-circuit via `rios.Exit(N)` without the binary
// needing extra plumbing.
func ExitCode(err error) int {
	if err == nil {
		return 0
	}
	var ee *rtk.EarlyExit
	if errors.As(err, &ee) {
		return ee.Code
	}
	return 1
}
